### ISSUE TITLE
VirtIO SCSI device is not bootable

### ISSUE THREAD

**Issue by raczkow** [TheGrandWazoo/freenas-proxmox#10]
When I create VirtIO SCSI hard drive, it is not recognized as bootable device in VM.
A can boot VM from CD, install system on hdd, but I can't boot system from the hdd.

Booting from VirtIO Block device works OK.

**Comment by raczkow** [comment]
BIOS so far. I'll ty UEFI in a moment.

**Comment by raczkow** [comment]
UEFI works OK.

**Comment by TheGrandWazoo** [comment]
I believe this is not a function of the FreeNAS plugin for Proxmox. Closing this issue.
