### ISSUE TITLE
Proxmox Update Error: Sub-process dpkg returned an error code (1)

### ISSUE THREAD

**Issue by AdamC1228** [TheGrandWazoo/freenas-proxmox#101]
I am getting the following when running apt install freenas-proxmox that seems to be a regression of issue #100 or very similar. 

Version:    6.4-11
Updates:  Fully Patched

![image](https://user-images.githubusercontent.com/13957003/124653535-68707700-de6b-11eb-93db-e05b7c20a71e.png)

**Comment by andrew-newell** [comment]
Proxmox 7.0-2 also reproduces this behavior

**Comment by andrew-newell** [comment]
> Proxmox 7.0-2 also reproduces this behavior

Apparently I did something to make the plugin work. I'm not exactly sure what I did but I'm reasonably sure it was a simple reboot + another run of `apt install freenas-proxmox` and now it works!

**Comment by TheGrandWazoo** [comment]
Closing with commit 55f699e0b137ad4d63c1a73db6238720eb86737c fixing the issues.
