### ISSUE TITLE
Patching error: post-installation script subprocess returned error exit status 1

### ISSUE THREAD

**Issue by lingfish** [TheGrandWazoo/freenas-proxmox#103]
`pve-manager/6.4-13/9f411e79 (running kernel: 5.4.78-2-pve)`

After manually doing:

```
  780  dpkg --unpack freenas-proxmox_2.0.2-3_all.deb
  781  dpkg --configure freenas-proxmox |& tee /tmp/out.txt
```

And then tweaking the `postinst` to see more verbosity, I'm getting:

```
Patching /usr/share/pve-manager/js/pvemanagerlib.js
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- pvemanagerlib.js.orig      2021-03-09 02:22:47.000000000 -0500
|+++ pvemanagerlib.js   2021-03-20 11:52:39.694828636 -0400
--------------------------
patching file /usr/share/pve-manager/js/pvemanagerlib.js
Using Plan A...
Hunk #1 succeeded at 7900 (offset 51 lines).
Hunk #2 succeeded at 47369 (offset 494 lines).
Hunk #3 succeeded at 47382 (offset 494 lines).
Hunk #4 FAILED at 46925.
Hunk #5 succeeded at 47435 (offset 494 lines).
Hunk #6 succeeded at 47445 (offset 494 lines).
Hunk #7 succeeded at 47460 (offset 494 lines).
Hunk #8 succeeded at 47517 (offset 494 lines).
Hunk #9 succeeded at 47527 (offset 494 lines).
1 out of 9 hunks FAILED -- saving rejects to file /usr/share/pve-manager/js/pvemanagerlib.js.rej
done
```

The reject is this:

```
--- pvemanagerlib.js.orig       2021-03-09 02:22:47.000000000 -0500
+++ pvemanagerlib.js    2021-03-20 11:52:39.694828636 -0400
@@ -46925,6 +46943,7 @@
     },

     setValues: function diff(values) {
+       values.freenas_confirmpw = values.freenas_password;
        values.writecache = values.nowritecache ? 0 : 1;
        this.callParent([values]);
     },

```

**Comment by TheGrandWazoo** [comment]
If you are using the stable repo, my automation needs a change due to changed on the backend GitHub. I will post a fix shortly.

**Comment by TheGrandWazoo** [comment]
My apologies for not getting a patch ready for 7.0 of Proxmox. I lost power for a few days and lost some of my equipment so needed to get replacements.
I also lost a switch at the Colo I am out of and Proxmox LACP didn't converge the network on the other switch, kind of weird but I am still trying to fix that.
So I finally upgraded to 7.x and replicated the issues which is confusing cause it works in 6 but not is 7 so I am coming up with a fix to suits both versions.
I'll get this up as soon as my Colo network gets stable so it can serve updates again.
Thanks for your patience.

**Comment by TheGrandWazoo** [comment]
Fixing the automation due to deprecated features at GitHub. Should be submitted to the stable branch today.

Closing with commit 55f699e0b137ad4d63c1a73db6238720eb86737c fixing the issues.

**Comment by lingfish** [comment]
Thanks for this. Haven't tried it yet.

I'm confused as to why you're referring to version 7 though? I'm on 6...
