### ISSUE TITLE
Proxmox VE 7.0 stable released. Is freenas-proxmox compatible?

### ISSUE THREAD

**Issue by hunter-nl** [TheGrandWazoo/freenas-proxmox#104]
Proxmox VE 7.0 stable has been released on July 6th. Is freenas-proxmox already compatible with this version?

**Comment by TheGrandWazoo** [comment]
My apologies for not getting a patch ready for 7.0 of Proxmox. I lost power for a few days and lost some of my equipment so needed to get replacements.
I also lost a switch at the Colo I am out of and Proxmox LACP didn't converge the network on the other switch, kind of weird but I am still trying to fix that.
So I finally upgraded to 7.x and replicated the issues which is confusing cause it works in 6 but not is 7 so I am coming up with a fix to suits both versions.
I'll get this up as soon as my Colo network gets stable so it can serve updates again.
The current beta patch applies but a HASH REF error occurs on 7.x when it didn't on 6.x but I have a fix, just making sure it works with 6.x so it will work when you upgrade to 7.x.
Thanks for your patience.

**Comment by TheGrandWazoo** [comment]
Both the 'testing' and 'stable' branches of the repo now support Proxmox 6 and 7 along with the migration from 6 to 7.

**Comment by TheGrandWazoo** [comment]
Closing with commit 55f699e0b137ad4d63c1a73db6238720eb86737c.
