### ISSUE TITLE
repo site not available anymore?

### ISSUE THREAD

**Issue by hunter-nl** [TheGrandWazoo/freenas-proxmox#105]
Is http://repo.ksatechnologies.com site not available anymore?

**Comment by TheGrandWazoo** [comment]
I lost a switch at the Colo I am serverd out of and Proxmox LACP didn't converge the network on the other switch, kind of weird but I am still trying to fix that. New switch in place but I might need to reboot the servers to have it all re-converge correctly.

Thanks for your patience.

**Comment by hunter-nl** [comment]
Repo is available again. Thank you.

**Comment by TheGrandWazoo** [comment]
Thanks for your patience!!
