### ISSUE TITLE
Wrong device prefix

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#114]
## Wrong device prefix

Log:

```
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-500-disk-4' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-500-disk-5' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-500-disk-6' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-500-disk-7' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-500-disk-8' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-500-disk-9' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-501-cloudinit' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-501-disk-1' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-501-disk-2' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-502-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-502-disk-1' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-502-disk-2' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-503-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-504-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-505-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-506-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-507-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-508-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-509-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-600-cloudinit' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-600-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing '/dev//storage/vm-disks/vm-601-disk-0' and '/dev/zvol/storage/vm-disks/vm-500-disk-9'
Mar 06 01:07:04 vm pvedaemon[653601]: PVE::Storage::LunCmd::FreeNAS::run_list_lu(/dev/zvol/storage/vm-disks/vm-500-disk-9) : name : lun not found
```

Root cause:
https://github.com/TheGrandWazoo/freenas-proxmox/blob/08bd48f35cf5c4451c6a19b95722c4643d5f13f0/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L410
https://github.com/TheGrandWazoo/freenas-proxmox/blob/08bd48f35cf5c4451c6a19b95722c4643d5f13f0/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L210

**Comment by TheGrandWazoo** [comment]
Moved issue from #110

**Comment by hans00** [comment]
Error when regenerate cloud-init image:
```
 : Verifing '/dev/zvol//storage/vm-disks/vm-507-disk-0' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
 : Verifing '/dev/zvol//storage/vm-disks/vm-508-disk-0' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
 : Verifing '/dev/zvol//storage/vm-disks/vm-509-disk-0' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
 : Verifing '/dev/zvol//storage/vm-disks/vm-600-cloudinit' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
 : Verifing '/dev/zvol//storage/vm-disks/vm-600-disk-0' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
 : Verifing '/dev/zvol//storage/vm-disks/vm-601-disk-0' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
 : Verifing '/dev/zvol//zvol/storage/vm-disks/vm-300-cloudinit' and '/dev/zvol/storage/vm-disks/vm-300-cloudinit'
(/dev/zvol/storage/vm-disks/vm-300-cloudinit) : name : lun not found
udinit at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 118.
```

And I know why this bug.

I use API batch create extents without prefix `zvol/`, but this line will include `zvol/`.

https://github.com/TheGrandWazoo/freenas-proxmox/blob/08bd48f35cf5c4451c6a19b95722c4643d5f13f0/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L522


In TrueNAS SCALE UI is no `zvol/`, so `zvol/` should remove also.

**Comment by TheGrandWazoo** [comment]
The syslog of the run_list_lu method does NOT include the $dev_prefix variable, only on the conditional:
https://github.com/TheGrandWazoo/freenas-proxmox/blob/08bd48f35cf5c4451c6a19b95722c4643d5f13f0/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L209-L210

This is also true in the run_list_extent method:
https://github.com/TheGrandWazoo/freenas-proxmox/blob/08bd48f35cf5c4451c6a19b95722c4643d5f13f0/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L235-L236

So the output you are seeing does NOT include that $dev_prefix.
So in reality, I "think" it's doing evaluating '/dev//dev/zvol//storage/vm-disks/vm-600-cloudinit'

Currently in my debugging, I have changed that to include the $dev_prefix in the syslog output to reflect the conditional.

Looks like I need to create some logic to 
1) Remove //
2) See if a /dev is already prepended to the results that come back from TrueNAS-Scale.

But this could also be the issue:
https://github.com/TheGrandWazoo/freenas-proxmox/blob/08bd48f35cf5c4451c6a19b95722c4643d5f13f0/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L116-L118
Which is called from the Proxmox parent methods.

So, if I am reading this correctly, you are telling me that you did NOT use the UI but direct to the API via like Postman to create these extents?

**Comment by hans00** [comment]
> The syslog of the run_list_lu method does NOT include the $dev_prefix variable, only on the conditional:

The `$dev_prefix` of log just for debug, 

> So, if I am reading this correctly, you are telling me that you did NOT use the UI but direct to the API via like Postman to create these extents?

Yes I create the extents without PVE.
The extent target device created by PVE is like `zvol/pool-name/vol-name`, but correct should be `pool-name/vol-name`.

**Comment by TheGrandWazoo** [comment]
I need more information of why all of a sudden that the pool name should be this pool-name/vol-name I am assuming on the TrueNAS side when it has always been zvol/pool-name/vol-name for the life of the plugin.

I have tested using the GUI to add, delete, remove till I am blue in the face against TrueNAS-Scale and have no problems.

Creating extents outside the GUI, I am going to say, is unsupported because of this exact reason.

I have no problems enhancing the product but changing something that already works for others that have used the product via the GUI and then removing the 'zvol' will break others. I could code around it but then it is getting more customized for a single purpose.

I need good reason and discussion from the community on this subject to continue.

**Comment by hans00** [comment]
At least add document for this issue. (Create extend manually should add `zvol/`)

This problem is because I reinstalled (reconfigure) the TrueNAS.

**Comment by TheGrandWazoo** [comment]
I have moved my images from my TrueNAS-Core to TrueNAS-Scale and have not had any issues.
I have also created new volumes on TrueNAS-Scale using the UI without issue.
What is the issue with using the /dev/zvol or just zvol in the path? It has been used since I forked it from the original developer. I know that most of the iSCSI commands our done in the "Proxmox" storage libs outside of the TrueNAS plugin.

Maybe I need to decouple the FreeNAS and make it it's own plugin instead of a Child off of ZFSPlugin.pm, but that would be a total rewrite but it would use FULL API calls to create everything instead of iscsiadm over SSH.

**Comment by TheGrandWazoo** [comment]
Due to not using the UI of Proxmox the configuration was not what the Plugin expected.
Will add some documentation that will say if you are not using the Proxmox VE UI for configuration of the [Free|True]NAS plugin then it is not supported.
Unless someone has a good argument for it?
