### ISSUE TITLE
Unable to download repo file

### ISSUE THREAD

**Issue by mrhanman** [TheGrandWazoo/freenas-proxmox#116]
I see there is a message that your moving colo's. Is there any update for when the repo will be online again?

**Comment by TheGrandWazoo** [comment]
Yes, I am currently looking a Jfrog for the repo and trying to get my automation changed to push to JFrog.
Just a learning curve at the moment.

**Comment by btobolaski** [comment]
Is there a way I can get the deb? I was trying to get a new node up and running but I use freenas for storage. I wouldn't mind hosting the repository.

**Comment by TheGrandWazoo** [comment]
[freenas-proxmox_2.2.0-0-beta1_all.deb.gz](https://github.com/TheGrandWazoo/freenas-proxmox/files/8695196/freenas-proxmox_2.2.0-0-beta1_all.deb.gz)

Try that.

**Comment by TheGrandWazoo** [comment]
Please see the README.md or the main page of the Project for the new repo and how to install it.
