### ISSUE TITLE
Issues after upgrading Truenas Core to 13.0-stable

### ISSUE THREAD

**Issue by mvdheenux** [TheGrandWazoo/freenas-proxmox#117]
After upgrading my Truenas server to version 13.0-stable (which also includes an upgrade to freebsd 13) the plugin no longer seems to work correctly (it worked flawlessly on Truenas 12-u8). 
I'm unable to start any of my VMs that have a disk in any of the zfs pools on my NAS, as well as being unable to create new disks. 

When starting a VM I'm. greeted with the following error message: 
()
Use of uninitialized value $truenas_version in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 411.
Use of uninitialized value $truenas_version in numeric ge (>=) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 412.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
TASK ERROR: Could not find lu_name for zvol vm-109-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 118.

And when creating a new disk I see the following: 
()
update VM 109: -scsi1 truenas1-SSD_2:20,backup=0,ssd=on,cache=writeback
Warning: volblocksize (4096) is less than the default minimum block size (8192).
To reduce wasted space a volblocksize of 8192 is recommended.
Use of uninitialized value $truenas_version in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 411.
Use of uninitialized value $truenas_version in numeric ge (>=) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 412.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
TASK ERROR: Unable to find the target id for iqn.2022-00.net.vdhee.truenas1:proxmox at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 259.

and

failed to update VM 109: Unable to find the target id for iqn.2022-00.net.vdhee.truenas1:proxmox at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 259. (500)

If I can help by supplying any more data, please let me know! 
Running Proxmox 7.2-3

**Comment by mvdheenux** [comment]
Here's some more output from the logfiles: 

May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : called
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '10.250.1.24'
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
May 13 02:06:11 think02 pvedaemon[429635]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : Response code: 302
May 13 02:06:11 think02 pvedaemon[429635]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : Response content: <html>
                                           <head><title>302 Found</title></head>
                                           <body>
                                           <center><h1>302 Found</h1></center>
                                           <hr><center>nginx</center>
                                           </body>
                                           </html>
May 13 02:06:11 think02 pvedaemon[429635]: Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : successful :
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_list_lu : successful
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : called with (method: 'create_lu'; result_value_type: 'name'; param[0]: '/dev/zvol/SSD_1/vm-109-disk-5')
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : TrueNAS object to find: '/dev/zvol/SSD_1/vm-109-disk-5'
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::run_list_lu '/dev/zvol/SSD_1/vm-109-disk-5' with key 'name' was not found
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : called
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '10.250.1.24'
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
May 13 02:06:11 think02 pvedaemon[429635]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : Response code: 302
May 13 02:06:11 think02 pvedaemon[429635]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : Response content: <html>
                                           <head><title>302 Found</title></head>
                                           <body>
                                           <center><h1>302 Found</h1></center>
                                           <hr><center>nginx</center>
                                           </body>
                                           </html>
May 13 02:06:11 think02 pvedaemon[429635]: Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
May 13 02:06:11 think02 pvedaemon[429635]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : successful :
May 13 02:06:11 think02 pvedaemon[429635]: VM 109 creating disks failed
May 13 02:06:11 think02 pvedaemon[429635]: Unable to find the target id for iqn.2022-00.net.vdhee.truenas1:proxmox at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 259.
May 13 02:06:11 think02 pvedaemon[1600]: <root@pam> end task UPID:think02:00068E43:008306F2:627DA0F3:qmconfig:109:root@pam: Unable to find the target id for iqn.2022-00.net.vdhee.truenas1:proxmox at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 259.


Seems like the API isn't giving the response it's expecting.

**Comment by TheGrandWazoo** [comment]
So 302 if a redirect so something in TrueNAS 13 is different. I will have to create a TrueNAS 13 VM and figure it out.

**Comment by TheGrandWazoo** [comment]
Installing TrueNAS 13.0 in a VM to test.

**Comment by mvdheenux** [comment]
Thanks for responding so quickly!

**Comment by TheGrandWazoo** [comment]
So it looks like V1.0 api's are no longer in the v13 of TrueNAS so it returns a webpage and NOT a 302 like it did before.

A workaround to this is editing the FreeNAS.pm and changing line 23 which has 
`my $apiping = '/api/v1.0/system/version/'; # Initial API method for setup`
to
`my $apiping = '/api/v2.0/system/version/'; # Initial API method for setup`

Yep, just change it from 1 to 2 and it should work.
You will probably need to restart the pvedaemon and pveproxy services for it to take effect.

I just need to figure out logic to compensate for the non-existence of the 302 in the V1.0 api or something else.

**Comment by TheGrandWazoo** [comment]
It also looks like the version format changed in v13.

**Comment by mvdheenux** [comment]
I've tried your quick fix, doesn't seem to have changed much for me (I've restarted the mentioned services, and later the entire host to make sure). 

Getting the following error when adding a disk to a random VM: 
()	
update VM 109: -scsi1 truenas1-SSD_2:1
Warning: volblocksize (4096) is less than the default minimum block size (8192).
To reduce wasted space a volblocksize of 8192 is recommended.
Use of uninitialized value $truenas_version in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 411.
Use of uninitialized value $truenas_version in numeric ge (>=) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 412.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 769.
TASK ERROR: Unable to find the target id for iqn.2022-00.net.vdhee.truenas1:proxmox at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 259.

**Comment by TheGrandWazoo** [comment]
Please issue the following to get the latest fix.
apt-get reinstall freenas-proxmox

This should execute the package installer and download the latest fixes for TrueNAS 13.

**Comment by jessiebryan** [comment]
> Please issue the following to get the latest fix.
> `apt-get reinstall freenas-proxmox`
> This should execute the package installer and download the latest fixes for TrueNAS 13.

@TheGrandWazoo - is your repo working? It's either timing out, or sending a 403 forbidden for myself.

**Comment by TheGrandWazoo** [comment]
I lock myself out of JFrog. Trying to resolve now.

**Comment by jessiebryan** [comment]
I manually patched my copy of LunCmd/FreeNAS.pm since the repo was not available for me.

I was able to create VMs - but Live Migrations reported an error - if this is related to TrueNAS 13, let me know and I can provide more assistance.


```2022-05-20 11:26:34 use dedicated network address for sending migration traffic (192.168.240.61)
2022-05-20 11:26:34 starting migration of VM 202205200 to node 'pve-r630-d' (192.168.240.61)
2022-05-20 11:26:34 starting VM 202205200 on remote node 'pve-r630-d'
2022-05-20 11:26:36 [pve-r630-d] Loop recursion prevention at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 357.
2022-05-20 11:26:36 ERROR: online migrate failure - remote command failed with exit code 255
2022-05-20 11:26:36 aborting phase 2 - cleanup resources
2022-05-20 11:26:36 migrate_cancel
2022-05-20 11:26:37 ERROR: migration finished with problems (duration 00:00:04)
TASK ERROR: migration problems

**Comment by TheGrandWazoo** [comment]
I can't seem to get your scenario to fail like you have above. Are you migrating Disk or the VM?
If you can please paste the syslog from 'both' Proxmox during this migration.

Also, make sure that you 'manually' patch ALL Proxmox VE Hypervisors with FreeNAS.pm and performed 'pvedaemon restart' and 'pveproxy restart'.

**Comment by jessiebryan** [comment]
I re-tested today after running both of the restart commands. I am having the same issue. For what it's worth, I'm getting the same "Loop recursion" output while trying to backup the VM.


Source syslog:
```
May 21 09:57:36 pve-r630-e pvedaemon[48554]: <root@pam> starting task UPID:pve-r630-e:00000908:0489FCEA:62891A00:qmigrate:202205200:root@pam:
May 21 09:57:39 pve-r630-e pmxcfs[13196]: [status] notice: received log
May 21 09:57:39 pve-r630-e pmxcfs[13196]: [status] notice: received log
May 21 09:57:41 pve-r630-e pmxcfs[13196]: [status] notice: received log
May 21 09:57:41 pve-r630-e pmxcfs[13196]: [status] notice: received log
May 21 09:57:41 pve-r630-e pvedaemon[2312]: migration problems
May 21 09:57:41 pve-r630-e pvedaemon[48554]: <root@pam> end task UPID:pve-r630-e:00000908:0489FCEA:62891A00:qmigrate:202205200:root@pam: migration problems
```

Migration Task view:
```
2022-05-21 09:57:37 use dedicated network address for sending migration traffic (192.168.240.61)
2022-05-21 09:57:37 starting migration of VM 202205200 to node 'pve-r630-d' (192.168.240.61)
2022-05-21 09:57:38 starting VM 202205200 on remote node 'pve-r630-d'
2022-05-21 09:57:39 [pve-r630-d] Loop recursion prevention at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 357.
2022-05-21 09:57:39 ERROR: online migrate failure - remote command failed with exit code 255
2022-05-21 09:57:39 aborting phase 2 - cleanup resources
2022-05-21 09:57:39 migrate_cancel
2022-05-21 09:57:41 ERROR: migration finished with problems (duration 00:00:04)
TASK ERROR: migration problems
```

Destination syslog:
```
May 21 09:57:33 pve-r630-d pmxcfs[6227]: [status] notice: received log
May 21 09:57:38 pve-r630-d pmxcfs[6227]: [status] notice: received log
May 21 09:57:47 pve-r630-d pmxcfs[6227]: [status] notice: received log
```

Also - Backup VM Task view:
```
INFO: starting new backup job: vzdump 202205200 --node pve-r630-e --storage PBS --mode snapshot --remove 0
INFO: Starting Backup of VM 202205200 (qemu)
INFO: Backup started at 2022-05-21 10:01:41
INFO: status = running
INFO: VM Name: pve-zfs-iscsi
ERROR: Backup of VM 202205200 failed - Loop recursion prevention at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 357.
INFO: Failed at 2022-05-21 10:01:41
INFO: Backup job finished with errors
TASK ERROR: job errors

**Comment by TheGrandWazoo** [comment]
Interesting...I would expect to see something like this on the Node->System->Syslog when doing a backup...
```
May 21 13:34:16 pve04-hq systemd[1]: user-0.slice: Consumed 3.305s CPU time.
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : list_lu(/dev/zvol/StorageTank/Proxmox/vDisks/vm-104-disk-0)
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection header Content-Type:'text/html'
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Changing to v2.0 API's
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection header Content-Type:'text/plain; charset=utf-8'
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection successful to '192.168.69.92' using the 'https' protocol
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : successful : Server version: TrueNAS-13.0-RELEASE
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : TrueNAS Unformatted Version: 13000000
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : Using TrueNAS API version v2.0
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_globalconfiguration : called
May 21 13:34:16 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.69.92'
May 21 13:34:17 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
May 21 13:34:17 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_globalconfiguration : target_basename=iqn.2022-05.com.ksatechnologies.truenas-core.ctl
May 21 13:34:17 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_list_lu : called
May 21 13:34:17 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
May 21 13:34:17 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.69.92'
May 21 13:34:17 pve04-hq pvedaemon[72256]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
```
This is the beginning snippet from the backup job I just ran on a VM with storage attached to TrueNAS-Core 13.

**Comment by jessiebryan** [comment]
I just realized you're on TrueNAS-Core, and I'm TrueNAS-SCALE-22.02.1, sorry about that.

Would you prefer a separate issue created to dive into this?

**Comment by mvdheenux** [comment]
I'm still having trouble getting this to work on Truenas core 13. Same issues & logs as before. 
I've applied your fixes & retarted the daemon & proxy services. Also tried removing the storage definitions & readding them in the Proxmox interface. Still getting "unable to find Target_ID". If I can help out by providing any more information, please let me know!

**Comment by TheGrandWazoo** [comment]
Ok, so what I need you to do if perform the operation that requires the TrueNAS 13 service and tell me what that operation is (e.g.-create a disk, migrate, backup). Then goto the Node->System-.Syslog and copy and paste from the point the TrueNAS plugin starts to the end...Sort of like I did above.
Then I can see what is happening.

**Comment by mvdheenux** [comment]
Hi, thanks again for the quick response ;). I might have spoken too soon. 
It must've been my own stupidity, somewhere. I've created a truenas core 13 VM for testing, with which this plugin works flawlessly. I'm going to reinstall my NAS, that must fix it for me ;).
