### ISSUE TITLE
Repo access forbidden?

### ISSUE THREAD

**Issue by hunter-nl** [TheGrandWazoo/freenas-proxmox#120]
I receive this error. Repo not OK?

http://repo.ksatechnologies.com/debian/pve/ksatechnologies-release.gpg
Resolving repo.ksatechnologies.com (repo.ksatechnologies.com)... 104.198.68.46
Connecting to repo.ksatechnologies.com (repo.ksatechnologies.com)|104.198.68.46|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-05-26 12:19:20 ERROR 403: Forbidden.

**Comment by dkowis** [comment]
Same as #116 and the Readme mentions that that old repo isn't available right now.

**Comment by TheGrandWazoo** [comment]
For now, this is temporary
```
curl -1sLf \
  'https://dl.cloudsmith.io/public/ksatechnologies/truenas-proxmox/setup.deb.sh' \
  | sudo -E bash
```
Run that from a command line on Proxmox.

**Comment by TheGrandWazoo** [comment]
New instructions and repo are now available and are posted in the README.md and on the main page of the Project.
