### ISSUE TITLE
had to disable old repo before running new cloudsmith repo script

### ISSUE THREAD

**Issue by gawong** [TheGrandWazoo/freenas-proxmox#121]
Had to rename old repo file before new cloudsmith script would run w/o apt update error:

mv /etc/apt/sources.list.d/ksatechnologies-repo.list /etc/apt/sources.list.d/ksatechnologies-repo.list.disabled

curl -1sLf \
  'https://dl.cloudsmith.io/public/ksatechnologies/truenas-proxmox/setup.deb.sh' \
  | sudo -E bash

**Comment by TheGrandWazoo** [comment]
There is a new repo available. Please see the README.md or the main page of the project.

**Comment by TheGrandWazoo** [comment]
New instructions are now posted in the README.md file and on the Main Page of the Project.
