### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [TheGrandWazoo/freenas-proxmox#123]
Hello, 

Thank you for your efforts bringing this to the masses!

I'm in the process of setting freenas-proxmox up on my x86 hosts but also on my RaspberryPI 4 node cluster. It seems (obviously) that there is no arm64 support. 
`N: Skipping acquire of configured file 'testing/binary-arm64/Packages' as repository 'https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bullseye InRelease' doesn't support architecture 'arm64'`

Would this be a hard to add? Will certainly contribute financially if this gets implemented.

ARM PVE repo:
https://raw.githubusercontent.com/pimox/pimox7

Thanks again, have a great day.

**Comment by TheGrandWazoo** [comment]
No real binary involved just perl scripts and diff files, so I don't see why not.
Give me a bit to see what I can do.

**Comment by TheGrandWazoo** [comment]
Not sure if it worked but give it a try.
