### ISSUE TITLE
after Zfs to iSCSI stuck at command: '/usr/bin......

### ISSUE THREAD

**Issue by Pacifichn** [TheGrandWazoo/freenas-proxmox#125]
Dear sir,
can you help me, after Zfs to iSCSi storage on proxmox stuck at here. Thanks
![screenshot_1665812554](https://user-images.githubusercontent.com/114474196/195971014-5a5c66e3-f817-4483-bb57-36f326f10767.jpeg)

command '/usr/bin/ssh -o 'BatchMode=yes' -i /etc/pve/priv/zfs/10.55.5.141_id_rsa root@10.55.5.141 zfs list -o name,volsize,origin,type,refquota -t volume,filesystem -Hrp' failed: exit code 255 (500)

**Comment by TheGrandWazoo** [comment]
You must do the following procedure:

https://github.com/TheGrandWazoo/freenas-proxmox#note-please-be-aware-that-this-plugin-uses-the-truenas-apis-but-still-uses-ssh-keys-due-to-the-underlying-proxmox-ve-perl-modules-that-use-the-iscsiadm-command

Seems to be your issue from what you have posted.
