### ISSUE TITLE
Reassign Owner / moving virtual disk between VMs not supported

### ISSUE THREAD

**Issue by linkstat** [TheGrandWazoo/freenas-proxmox#127]
In Proxmox, go to any VM with al most one _ZFS over iSCSI_ configured disk. Select the disk, and choose `Disk Action` -> `Reassign Owner` option from the menu. In `Target Guest`, select any other VM (stopped or running, doesn't matter), select an appropiate `Bus/Device` and clic on `Reassign Disk` button. After the _Please wait..._ message, the following error is displayed:

> Storage does not support moving of this disk to another VM (500)

Regards!

**Comment by TheGrandWazoo** [comment]
So in Proxmox they have a data structure that check for the feature "rename"
```
                die "Storage does not support moving of this disk to another VM\n"
                if (!PVE::Storage::volume_has_feature($storecfg, 'rename', $source_volid));
```
In the Proxmox Storage libs, the only Volumes supporting the 'rename' feature are:
```
LVM
LVMThin
RBD
ZFSPool
```
The ZFS over iSCSI uses the ZFSPlugin and does not have that feature enabled as of this version.

ZFSPlugin.pm
```
sub volume_has_feature {
    my ($class, $scfg, $feature, $storeid, $volname, $snapname, $running) = @_;

    my $features = {
        snapshot => { current => 1, snap => 1},
        clone => { base => 1},
        template => { current => 1},
        copy => { base => 1, current => 1},
    };
```
LVMPlugin.pm
```
sub volume_has_feature {
    my ($class, $scfg, $feature, $storeid, $volname, $snapname, $running) = @_;

    my $features = {
        copy => { base => 1, current => 1},
        rename => {current => 1},
    };

    my ($vtype, $name, $vmid, $basename, $basevmid, $isBase) =
        $class->parse_volname($volname);
```

Notice LVMPlugin.pm has the feature 'rename' and ZFSPlugin.pm does not.

This is working as designed by Proxmox.
