### ISSUE TITLE
TPM support on TrueNAS

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#136]
The only issue im having now that i have got far enough is the tpm. Is there any way you can enable support so i can store my tpms with the bootdrives?

_Originally posted by @awptechnologies in https://github.com/TheGrandWazoo/freenas-proxmox/issues/134#issuecomment-1507488613_

**Comment by TheGrandWazoo** [comment]
I myself, back almost a year, was trying to get it to work and found that it was not part of the supported storage for TPM. I had to use CEPH between all the Nodes so they could Migrate correctly.

I just created a tested VM with disks on different TrueNAS deployments and I am now able to migrate a VM with EFI and TPM disks on TrueNAS.

Let me know what error you are receiving so I can see what might be happening.

I am going to see if I can convert one more my running VM to totally use TrueNAS Core/Scale.

**Comment by TheGrandWazoo** [comment]
The underlying PVE Perl module `/usr/share/perl5/PVE/QemuServer.pm` has a hardcoded `file://$state` value in the call to `swtpm_setup`. Due to `$state` value being something like `iscsi://stuff` then it will then become `file://iscsi://stuff` which is not valid.
Commented out the `file://$state` line and just using the variable `$state` provided a different error that it could not find the file.
At the moment this is a Proxmox VE or the `swtpm_setup` command limitation.

**Comment by awptechnologies** [comment]
iscsiadm: No session found.
iscsiadm: No session found.
iscsiadm: No session found.
iscsiadm: No session found.
/bin/swtpm exit with status 256: 
TASK ERROR: start failed: command 'swtpm_setup --tpmstate file://iscsi://My-IP/iqn.2023-04.MY DOMAIN.mars:vmz/6 --createek --create-ek-cert --create-platform-cert --lock-nvram --config /etc/swtpm_setup.conf --runas 0 --not-overwrite --tpm2 --ecc' failed: exit code 1


This is the actual error that shows up when trying to boot vm with tpm on the zfs over iscsi drive. OfCourse i changed my ip and domain name but you get the gist. Thanks for all the help. For real

**Comment by TheGrandWazoo** [comment]
Won't fix because this is an underlying feature in Proxmox that is will NOT use the ZFS over iSCSI modules for TPM drives.
