### ISSUE TITLE
401 Unauthorized on fresh install of TrueNAS Core 13.0-U4 and Proxmox VE 7.4

### ISSUE THREAD

**Issue by kaypeter87** [TheGrandWazoo/freenas-proxmox#138]
Hello!

First of all, thanks for the work done so far on this plugin. I'm so glad you've taken the time to write a plugin that is filling a gap in the Proxmox/TrueNAS space!

I wanted to try out your plugin but am running into a snag with VMs. I followed all of the instructions on installing your solution and creating all of the necessary keys, allowing root password/login, etc...

I am able to create the Storage on my Proxmox VE 7.4 cluster and I am able to see the available space and VM disks (ones that I try to migrate), but whenever I create a VM or migrate a disk to the ZFS storage I get the following error: 

```
Apr 23 01:04:54 proxmox pvedaemon[176773]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response code: 401
Apr 23 01:04:54 proxmox pvedaemon[176773]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response content: 401: Unauthorized
Apr 23 01:04:54 proxmox pvedaemon[171829]: unable to create VM 112 - Unable to connect to the FreeNAS API service at '192.168.1.108' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 380.
Apr 23 01:04:54 proxmox pvedaemon[49596]: <root@pam> end task UPID:proxmox:00029F35:19B48715:6444B7D3:qmcreate:112:root@pam: unable to create VM 112 - Unable to connect to the FreeNAS API service at '192.168.1.108' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 380.
```

What's odd is that when I try to migrate or create the disk, the VM Disks show up on the ZFS Storage (seen in proxmox) but doesn't fully process the migration. So I end up with my VM using the old disk but also creating the same disk in the ZFS Storage.

Any idea what might be causing the issue? Thanks!

**Comment by mdallaire** [comment]
I am seeing the same problem.

Proxmox 7.4-3
TrueNAS-SCALE-22.12.2
freenas-proxmox 2.2.0-0-beta10

I was able to confirm the API is accessible on the network and the credentials are also correct by testing with the Truenas Home-Assistant integration which is able to connect to the API without error.

```
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : create_lu(/dev/zvol/data01/vm-102-disk-0)
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection header Content-Type:'text/html'
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Changing to v2.0 API's
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
May 01 15:51:25 pve01 pvedaemon[74994]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection header Content-Type:'text/plain; cha>
May 01 15:51:25 pve01 pvedaemon[74994]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response code: 401
May 01 15:51:25 pve01 pvedaemon[74994]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response content: 401: Unauthor>
May 01 15:51:25 pve01 pvedaemon[74994]: storage migration failed: Unable to connect to the FreeNAS API service at '10.0.20.10' using the 'http' p>
```

**Comment by Buliwyf-Stonehand** [comment]
I had the same issue when I tried to use an _API Key_. What you actually have to enter as _API Username_ and _API Password_ are the credentials of a user account (e.g. root). The plugin uses _Basic Authentication_ instead of _Bearer Authentication_ and API Keys only work when used as a bearer token.

**Comment by kaypeter87** [comment]
Thanks, using the actual user/password via basic authentication resolves my issue. Using API Keys is not supported on the plugin as `Bearer Authentication` headers are not being used.
