### ISSUE TITLE
TrueNAS SCALE Support ?

### ISSUE THREAD

**Issue by ApolloDS** [TheGrandWazoo/freenas-proxmox#141]
Hi,
I just tried your project and I like it very much!
I use TrueNAS SCALE and there's no iscsadm command.

Do you plean to support the TN SCALE in the future?

**Comment by insunaa** [comment]
It already works with TrueNAS Scale. the icsadm command only needs to be present on Proxmox

**Comment by TheGrandWazoo** [comment]
@insunaa Is correct. The iscsiadm command is only used on the Proxmox nodes.
And TrueNAS Scale has been supported for some time now.
