### ISSUE TITLE
Cannot restore to ZFS pool

### ISSUE THREAD

**Issue by Pete1979** [TheGrandWazoo/freenas-proxmox#143]
Hi,

I cant restore to the ZFS pool from proxmox. I can create a new VM and proxmox creates a new disk.

But when i try to restore i get the following:

restore vma archive: zstd -q -d -c /mnt/pve/proxmox/dump/vzdump-qemu-111-2023_06_19-00_28_37.vma.zst | vma extract -v -r /var/tmp/vzdumptmp2307.fifo - /var/tmp/vzdumptmp2307
CFG: size: 574 name: qemu-server.conf
DEV: dev_id=1 size: 540672 devname: drive-efidisk0
DEV: dev_id=2 size: 34359738368 devname: drive-scsi0
CTIME: Mon Jun 19 00:29:17 2023
new volume ID is 'ssd:vm-111-disk-0'
new volume ID is 'ssd:vm-111-disk-1'
iscsiadm: No session found.
map 'drive-efidisk0' to 'iscsi://10.10.10.3/iqn.2005-10.org.freenas.ctl:zfsoveriscsi/0' (write zeros = 1)
iscsiadm: No session found.
map 'drive-scsi0' to 'iscsi://10.10.10.3/iqn.2005-10.org.freenas.ctl:zfsoveriscsi/1' (write zeros = 1)
vma: can't open file iscsi://10.10.10.3/iqn.2005-10.org.freenas.ctl:zfsoveriscsi/0 - iSCSI: Failed to connect to LUN : Failed to log in to target. Status: Target not found(515)
/bin/bash: line 1: 2309 Broken pipe zstd -q -d -c /mnt/pve/proxmox/dump/vzdump-qemu-111-2023_06_19-00_28_37.vma.zst
2310 Trace/breakpoint trap | vma extract -v -r /var/tmp/vzdumptmp2307.fifo - /var/tmp/vzdumptmp2307
temporary volume 'ssd:vm-111-disk-1' sucessfuly removed
temporary volume 'ssd:vm-111-disk-0' sucessfuly removed
no lock found trying to remove 'create' lock
error before or during data restore, some or all disks were not completely restored. VM 111 state is NOT cleaned up.
TASK ERROR: command 'set -o pipefail && zstd -q -d -c /mnt/pve/proxmox/dump/vzdump-qemu-111-2023_06_19-00_28_37.vma.zst | vma extract -v -r /var/tmp/vzdumptmp2307.fifo - /var/tmp/vzdumptmp2307' failed: exit code 1

Edit:
Solved following this guide for setting up iscsi.
https://forum.proxmox.com/threads/proxmox-ve-and-zfs-over-iscsi-on-truenas-scale-my-steps-to-make-it-work.125387/

**Comment by Pete1979** [comment]
I also tried moving the disks, restored to a NFS share and then "migrade disk" but that gave me this error:

**Comment by TheGrandWazoo** [comment]
Bad bot

**Comment by TheGrandWazoo** [comment]
Solved by user using the instruction at this link https://forum.proxmox.com/threads/proxmox-ve-and-zfs-over-iscsi-on-truenas-scale-my-steps-to-make-it-work.125387/
