### ISSUE TITLE
Proxmox 8 freenas-proxmox not available in bookworm repository

### ISSUE THREAD

**Issue by awptechnologies** [TheGrandWazoo/freenas-proxmox#146]
After upgrading to proxmox 8 everything is working fine. I get an error in the GUI because the repository for freenas-proxmox is only available in bullseye. I switched it to bookworm to try it and it failed. Can you make it available in the bookworm repository so I can get rid of the warning?

**Comment by gionag** [comment]
+1

**Comment by TheGrandWazoo** [comment]
Will be working on stuff this Holiday weekend.
One thing that I am not sure of is that Jfrog sent me an email message they were terminating my account on July 8th. I reached out and have not heard from them on the matter, so I am not sure if it is true or not.

**Comment by TheGrandWazoo** [comment]
Bookworm repo created. Give it a try.

**Comment by webtroter** [comment]
> Bookworm repo created. Give it a try.

I get this error on `apt update` :
> W: Conflicting distribution: https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm InRelease (expected bookworm but got bullseye)

**Comment by gionag** [comment]
> > Bookworm repo created. Give it a try.
> 
> I get this error on `apt update` : `W: Conflicting distribution: https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm InRelease (expected bookworm but got bullseye)`

indeed.
"Release" and "InRelease" both still reports bullseye
```
Origin: Artifactory
Label: Artifactory
Suite: bullseye
Codename: bullseye
```

**Comment by TheGrandWazoo** [comment]
Fixed.

**Comment by webtroter** [comment]
Thank you

I'm now having these warnings, because I'm using the testing releases (git main branch).

```
W: Skipping acquire of configured file 'testing/binary-amd64/Packages' as repository 'https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm InRelease' doesn't have the component 'testing' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'testing/i18n/Translation-en_US' as repository 'https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm InRelease' doesn't have the component 'testing' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'testing/i18n/Translation-en' as repository 'https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm InRelease' doesn't have the component 'testing' (component misspelt in sources.list?)
```

**Comment by TheGrandWazoo** [comment]
I didn't do the testing component. Should be fixed now.

**Comment by webtroter** [comment]
Thank you.

I was able to `apt update` without problems

`Get:12 https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm/testing amd64 Packages [571 B]`

**Comment by TheGrandWazoo** [comment]
Glad to hear it.
I also had the `proxmox-ve` removal issue. I fixed it by adding the `bookworm` to the ceph.list and all was good in the world again.
