### ISSUE TITLE
ProxMox 8.0 Support

### ISSUE THREAD

**Issue by wwalker0307** [TheGrandWazoo/freenas-proxmox#147]
Does this still work with Proxmox 8?

**Comment by TheGrandWazoo** [comment]
People have install with Proxmox 8.0 but I have not official installed it yet. That is my task for this Holiday weekend.

**Comment by TheGrandWazoo** [comment]
Upgraded my cluster to Proxmox 8.0-3 without issues following the procedures on the Proxmox site.
You can download the new truenas-proxmox repo file from https://ksatechnologies.jfrog.io/artifactory/ksa-repo-gpg/ksatechnologies-repo.list

**Comment by wwalker0307** [comment]
Confirmed migration works without issue.  The upgrade guide referenced by @TheGrandWazoo is here https://pve.proxmox.com/wiki/Upgrade_from_7_to_8
