### ISSUE TITLE
Problem with postinstall script

### ISSUE THREAD

**Issue by CMAPTu** [TheGrandWazoo/freenas-proxmox#149]
Today we have upgraded our proxmox cluster to 8.0 version, so we added bookworm repo for freenas-proxmox. We investigated that post-install script of freenas-proxmox doesn't run on installation\upgrade.

The error was:
`/bin/bash^M: bad interpreter: No such file or directory`

It seems that bash script in repo saved with  DOS codepage.
The workaround is to convert it to UNIX:
` vim /var/lib/dpkg/info/freenas-proxmox.postinst`
`:set ff=unix`
And then rerun install\upgrade.

**Comment by taos15** [comment]
sorry if im hijacking the issue, where did you fins the repo? Im struggling upgrading.

**Comment by Pete1979** [comment]
> Today we have upgraded our proxmox cluster to 8.0 version, so we added bookworm repo for freenas-proxmox. We investigated that post-install script of freenas-proxmox doesn't run on installation\upgrade.
> 
> The error was: `/bin/bash^M: bad interpreter: No such file or directory`
> 
> It seems that bash script in repo saved with DOS codepage. The workaround is to convert it to UNIX: ` vim /var/lib/dpkg/info/freenas-proxmox.postinst` `:set ff=unix` And then rerun install\upgrade.

Same question as taos15. Where did you find the bookworm repo, and how did you add it for freenas-proxmox?

**Comment by TheGrandWazoo** [comment]
JFrog has canceled my subscription for no reason. I am currently looking for other alternatives and will post a solution once I have something running.

**Comment by CMAPTu** [comment]
> > Today we have upgraded our proxmox cluster to 8.0 version, so we added bookworm repo for freenas-proxmox. We investigated that post-install script of freenas-proxmox doesn't run on installation\upgrade.
> > The error was: `/bin/bash^M: bad interpreter: No such file or directory`
> > It seems that bash script in repo saved with DOS codepage. The workaround is to convert it to UNIX: ` vim /var/lib/dpkg/info/freenas-proxmox.postinst` `:set ff=unix` And then rerun install\upgrade.
> 
> Same question as taos15. Where did you find the bookworm repo, and how did you add it for freenas-proxmox?

deb https://ksatechnologies.jfrog.io/artifactory/truenas-proxmox bookworm main
It's not available now

**Comment by eugenefvdm** [comment]
I run a hosting company, https://vander.host. 
I'm happy to sponsor free hosting of the repo(s) for as long as required (years).
Contact me at eugene (at) vander.host or +27 82 309 6710 (mobile call or WhatsApp)

**Comment by TheGrandWazoo** [comment]
postinst fixed in v2.2.0-1

**Comment by TheGrandWazoo** [comment]
> I run a hosting company, https://vander.host. I'm happy to sponsor free hosting of the repo(s) for as long as required (years). Contact me at eugene (at) vander.host or +27 82 309 6710 (mobile call or WhatsApp)

@eugenefvdm - Thanks for the offer. I have been weighing my options on private hosting and artifact-type hosting from providers. After testing, looking at pros and cons, and easy of use I think I have a solution an am currently fixing the docs for the final release.
