### ISSUE TITLE
MAX LUN limits

### ISSUE THREAD

**Issue by CMAPTu** [TheGrandWazoo/freenas-proxmox#150]
There is a variable in FreeNAS.pm script:

`$MAX_LUNS = 255;` 

As it follows from RedHat documentation: https://access.redhat.com/solutions/5120951 , this limit is not actual. So every time we install freenas-proxmox plugin, we have to edit script to enlarge this limit.

Please, make changes to the script. Set variable as big as it is possible.

**Comment by TheGrandWazoo** [comment]
Thanks for reporting it. I will review the Redhat document and figure out a solution.

**Comment by tuxick** [comment]
> There is a variable in FreeNAS.pm script:
> 
> `$MAX_LUNS = 255;`
> 
> As it follows from RedHat documentation: https://access.redhat.com/solutions/5120951 , this limit is not actual. So every time we install freenas-proxmox plugin, we have to edit script to enlarge this limit.
> 
> Please, make changes to the script. Set variable as big as it is possible.

Are you sure more than 255 is supported by freenas/truenas? [here](https://www.truenas.com/community/threads/maximum-number-of-luns-per-target-is-255.110645/) they suggest 256 luns is a hard limit.

**Comment by CMAPTu** [comment]
> > There is a variable in FreeNAS.pm script:
> > `$MAX_LUNS = 255;`
> > As it follows from RedHat documentation: https://access.redhat.com/solutions/5120951 , this limit is not actual. So every time we install freenas-proxmox plugin, we have to edit script to enlarge this limit.
> > Please, make changes to the script. Set variable as big as it is possible.
> 
> Are you sure more than 255 is supported by freenas/truenas? [here](https://www.truenas.com/community/threads/maximum-number-of-luns-per-target-is-255.110645/) they suggest 256 luns is a hard limit.

Yes, I am pretty sure of that. Here is the kernel variable value:
![изображение](https://github.com/TheGrandWazoo/freenas-proxmox/assets/98010588/6558c84f-a470-41cf-84fe-5301f9bef11f)
We successfully multiplied it by two in /boot/loader.conf of FreeNAS. After reboot it worked.

kern.cam.ctl.max_luns=2048

**Comment by TheGrandWazoo** [comment]
Bringing out of closed as this is as a few solutions.
