### ISSUE TITLE
Unsupported filetype in the keyring - JFrog Repo Down

### ISSUE THREAD

**Issue by Pete1979** [TheGrandWazoo/freenas-proxmox#151]
I updated to Proxmox 8 a while back. And everything worked as it should.

Today i got errors in my repos.
Running the Curl commands i get these errors after apt update:

W: http://ftp.debian.org/debian/dists/bookworm/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ksatechnologies-release.gpg are ignored as the file has an unsupported filetype.
W: http://download.proxmox.com/debian/pve/dists/bookworm/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ksatechnologies-release.gpg are ignored as the file has an unsupported filetype.
W: http://ftp.debian.org/debian/dists/bookworm-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ksatechnologies-release.gpg are ignored as the file has an unsupported filetype.
W: http://security.debian.org/debian-security/dists/bookworm-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ksatechnologies-release.gpg are ignored as the file has an unsupported filetype.

**Comment by webtroter** [comment]
@TheGrandWazoo , is there some manual install instruction somewhere?

I updated my proxmox (and commented out the jfrog repo) and now the iscsi session dont get established.

**Comment by webtroter** [comment]
I commented out the jfrog repo, ran `apt update && apt upgrade`, then I followed [Manual install of the freenas proxmox plugin](https://github.com/TheGrandWazoo/freenas-proxmox/wiki/Manual-install-of-the-freenas-proxmox-plugin:Archive) and it worked well.

**Comment by awptechnologies** [comment]
i already have it installed. was just trying to update it.
Honestly i can host the repo if thats even possible my servers dont do much and i can route it through a proxy on a vps if that helps.

**Comment by TheGrandWazoo** [comment]
New repo coming soon. Hopefully today after some testing. Thanks for your patience.

**Comment by TheGrandWazoo** [comment]
> > New repo coming soon. Hopefully today after some testing. Thanks for your patience.
> 
> I'll be happy to test when you go live :)
> 
> Thank you :)

Thank you. Appreciate the help.

**Comment by TheGrandWazoo** [comment]
New repos now available. #157

**Comment by TheGrandWazoo** [comment]
Closing due to being resolved. See README.md for details on using the new repos.
