### ISSUE TITLE
Problem with jfrog artifactory

### ISSUE THREAD

**Issue by Brav-o** [TheGrandWazoo/freenas-proxmox#153]
Hi,
I just saw that artifactory stopped you acconts.
Can you upload the 2 files for apt somewhere else ?

**Comment by Tradeforlife** [comment]
How's it going with setting up the new repository? Or how can I manually install it from source?

**Comment by Tradeforlife** [comment]
> New repo is coming soon. Hopefully today.
Great!! I built a new prox node and went to install the apt... whoops no go :) thanks for you work.. love it.

**Comment by TheGrandWazoo** [comment]
Duplicate of #151

**Comment by TheGrandWazoo** [comment]
New repos now available. #157

**Comment by TheGrandWazoo** [comment]
Closing due to being resolved. See README.md for details on using the new repos.
