### ISSUE TITLE
Paypal Donation Unavailable

### ISSUE THREAD

**Issue by cgg507** [TheGrandWazoo/freenas-proxmox#154]
Hey, I tried to Donate using the button in the main webpage of the github, however it does not seem to be working, as the following message is shown (screen capture attached)
![Image 08-02-23 at 5 42 AM](https://github.com/TheGrandWazoo/freenas-proxmox/assets/17771096/98c32581-0f9f-4f84-8d0c-4d4092b3e740)

**Comment by Creat** [comment]
I ran into the same problem, tried contacting via mail but haven't heard back (yet?).
I do hope this gets resolved soon, cause this is a project that deserves to be supported and quite frankly I rely on it (home lab environment, but still).

**Comment by amlucent** [comment]
> I ran into the same problem, tried contacting via mail but haven't heard back (yet?). I do hope this gets resolved soon, cause this is a project that deserves to be supported and quite frankly I rely on it (home lab environment, but still).

same boat as you. I tried to manually install after upgrading to proxmox 8 but its still not working.  All of my VMs wont start.  LXCs are on a LVM over iscsi volume so those are what I rely on more tbh. 

Honestly, outside looking in,  I think Proxmox Server Solutions GmbH or even IX Systems (Truenas) should be paying for @TheGrandWazoo's  JFrog artifactory development costs.  Either sponsor this project with funds or fork it and adopt the development in house. I think its the ONLY ZFS over iscsi solution for proxmox at all...  

I wonder if more "enterprise class" ZFS storage arrays like DDN Intelliflash or an Oracle ZFS arrays like I have at my employer use this plugin for proxmox or if their ZFS over iscsi "just works" without a plugin?

**Comment by eugenefvdm** [comment]
I paid @TheGrandWazoo a small amount via Paypal and offered to host the files. He didn't respond, and his Github says he's too busy. I guess this project is stalling.

Side question, I use TrueNAS with NFS and it works well and was super easy to configure. Any reason why I should be using iSCSI instead?

**Comment by amlucent** [comment]
> Side question, I use TrueNAS with NFS and it works well and was super easy to configure. Any reason why I should be using iSCSI instead?

https://pve.proxmox.com/pve-docs/chapter-pvesm.html

according to Table 1.: snapshots.  also you may get less latency with iscsi vs nfs.

**Comment by cgg507** [comment]
> Side question, I use TrueNAS with NFS and it works well and was super easy to configure. Any reason why I should be using iSCSI instead?

Block-level IO performance should be superior to File-level IO performance. I love the fact that this plugin does amazing things such as snapshots on the Storage end (which will show up as a separate entity in the TrueNAS GUI) and leverage ZFS tools to do so, emulating the behavior of offloading mechanisms such as VAAI or ODX.

Don't get me wrong, even enterprise-level products such as ESXi will work just fine with NFS-based storage, but in my 9-5 I've learn to love things such as multipathing, storage-based snapshots and/or replication, while TrueNAS provides some of those to an extent without a hefty pricetag.

**Comment by TheGrandWazoo** [comment]
New repo coming soon. Hopefully today.
Thanks for you patience.

**Comment by TheGrandWazoo** [comment]
Not sure what is going on with the Paypal but thank you for donating. I will look into this and see what the issue is.

**Comment by TheGrandWazoo** [comment]
Hi. I could not reproduce the PayPal issue. When you have a chance, please try again.

**Comment by eugenefvdm** [comment]
Yep same problem:

> The country you're trying to send money to can't receive this payment.
If you continue to encounter problems, please contact [customer service](https://www.paypal.com/selfhelp/home).


But please note around two weeks ago this worked from South Africa.

**Comment by TheGrandWazoo** [comment]
New repos now available. #157

**Comment by TheGrandWazoo** [comment]
Please check to see if the Paypal issue is resolved.

**Comment by eugenefvdm** [comment]
> Please check to see if the Paypal issue is resolved.

Hi yes it worked, I just donated and it went through. Thanks and keep up the good work. We love you.

**Comment by cgg507** [comment]
Hey, I just tried and it went through. Thanks for keeping up the good work!
