### ISSUE TITLE
Is Proxmox 8 supported?

### ISSUE THREAD

**Issue by dimasrespect** [TheGrandWazoo/freenas-proxmox#168]
Does it works with proxmox 8? I have cluster on proxmox 7, may I upgrade it to Proxmox 8 version? Are there any issues with that?

**Comment by TheGrandWazoo** [comment]
Yes is does. I have it working on my 4 Node cluster with ProxmoxVE 8!!! And I did the upgrade from ProxmoxVE 7 to ProxmoxVE 8 without issues.
