### ISSUE TITLE
Does it support TrueNAS Scale Cobia?

### ISSUE THREAD

**Issue by kmetsalu** [TheGrandWazoo/freenas-proxmox#171]
Im currently using ZFS over iSCSI method against bluefin.

**Comment by TheGrandWazoo** [comment]
I have not done any work with the Cobia. I will have to spin up an instance and see what happens.

**Comment by TheGrandWazoo** [comment]
Is this Cobia/Bluefin version 23.10.0.1?

**Comment by addelovein** [comment]
> Is this Cobia/Bluefin version 23.10.0.1?

yes, and root user will be deprecated  

for me the ssh tries to contact root@ which obviously fails since the ssh keys now are in admin user

**Comment by Dennis-Ayala** [comment]
> > Is this Cobia/Bluefin version 23.10.0.1?
> 
> yes, and root user will be deprecated
> 
> for me the ssh tries to contact root@ which obviously fails since the ssh keys now are in admin user...
> 
> Installing latest Scale with root user this plugin works as intended... However i could not get it working with the admin user....

I am having some issues with it and Proxmox 8.1.3. Please see https://github.com/TheGrandWazoo/freenas-proxmox/issues/174

Any help is appreciated.

Dennis
