### ISSUE TITLE
Iscsi no session found

### ISSUE THREAD

**Issue by awptechnologies** [TheGrandWazoo/freenas-proxmox#175]
anytime i do anything with the shell for example moving a vm disk to another iscsi over zfs drive i get the error iscsiadm no session found. As far as i can tell absolutely everything works its just an annoying error. Is there anyway to get rid of it?
![Screenshot 2024-01-30 130531](https://github.com/TheGrandWazoo/freenas-proxmox/assets/122591606/02499a11-25f1-496e-970f-ddba89b3a471)

**Comment by awptechnologies** [comment]
This is me moving a scsi0 drive of a vm to iscsi over zfs pool. I get all these errors but it is still transferring the disk and i don't seem to have any actual failures.
![Screenshot 2024-01-30 130705](https://github.com/TheGrandWazoo/freenas-proxmox/assets/122591606/513fd404-0c1a-43c5-a0b2-de623ef2b5f2)

**Comment by eugenefvdm** [comment]
I normally use the UI to move disks and I haven't had any errors.

1. Whilst setting up my system I had to do loads of `iscsiadm` and came up with a couple of diagnostic commands to help me check my config. Some of these were:

```
# iscsiadm --mode discovery --op update --type sendtargets --portal 192.168.1.254
```

That command should return:

```
192.168.1.254:3260,1 iqn.2005-10.org.freenas.ctl:target
``` 

2. I do get the volblocksize warning and ideally I'd like to get rid of it. I posted about it here:
https://forum.proxmox.com/threads/whilst-move-storage-from-local-lvm-to-truenas-zfs-over-iscsi-warning-volblocksize-4096-is-less-than-the-default-minimum-block-size-8192.135053/

**Comment by TheGrandWazoo** [comment]
I usually get those too. But the iscsiadm is a command in the Proxmox libs not the plugin.
