### ISSUE TITLE
Freenas-API not listed after Reboot

### ISSUE THREAD

**Issue by Marco3G** [TheGrandWazoo/freenas-proxmox#177]
Hi there

I just installed this plugin without beta repos:

freenas-proxmox/any-version,now 2.2.0-1 all [installed]
freenas-proxmox/any-version 2.0.0-1 all
freenas-proxmox/any-version 1.0.0-1 all

Proxmox is 8.1.4

However shouldn't I now be able to setup ZFS over iSCSI and select Freenas-API from the provider drop-down? For me it isn't listed... Do I need to activate it somewhere?

**Comment by surfrock66** [comment]
I am seeing this now as well, it is no longer listed in the UI.  Oddly, a prior lun made by the plugin shows it as the provider:
![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/1a9820db-ae65-4443-b345-fbd5cc8f011c)
![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/fc44c4f2-3ec8-4101-9942-b3aa49f6fe63)

Proxmox 8.1.10, plugin fully up to date stable channel.

**Comment by surfrock66** [comment]
This was resolved by a browser cache clear, which was weird, I don't know how it cached a version without the plugin.  I've had the plugin for years.

**Comment by TheGrandWazoo** [comment]
The UI must be refreshed due to changes in the Javascript code. That needs to be reloaded.
I will add some doc to the README.md to make sure you so a browser refresh after the installation or is there is another way to automatically do it.
