### ISSUE TITLE
API Parameter verification failed when adding ZFS over iSCSI

### ISSUE THREAD

**Issue by ADiefenbach** [TheGrandWazoo/freenas-proxmox#178]
Hi, is anybody else having the same issue?

This came up after upgrading to PVE 8 (8.1.4) if i try to configure ZFS over iSCSI in Proxmox. 

<img width="452" alt="image" src="https://github.com/TheGrandWazoo/freenas-proxmox/assets/160331463/87845780-d816-4668-8484-f0ca96b90464">

Data is located on TrueNAS Core TrueNAS-13.0-U6.1
This worked fine in the past, any idea what I can do?

**Comment by Pete1979** [comment]
I have this issue as well. 
Is it being looked at? I changed one of my node to a newer machine, but i cant migrate anything to it. Cant even make new VM on the new node.

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/5860889/bd6321dc-479f-4327-b7bd-f44463ab3bc3)

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/5860889/a9f4f568-b045-4986-bf52-7b690ca0ede6)


Edit:

I added the test repo and now i got past the Parameter issue, now i have another, but i think i have had this one before, trying to solve it.

TASK ERROR: Unable to connect to the FreeNAS API service at '192.168.0.60' using the 'https' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 389.

Its not the bind address in truenas, i have that set to wildcard. 0.0.0.0

**Comment by Pete1979** [comment]
I solved this by using the test repo from the install instructions. Then i hade a issue with the new node, it did not get any iscsi portals when i created the shares in proxmox, so i copied the folder /etc/iscsi from my working node to the new one, rebooted and got it working with API token.

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/5860889/c272f669-e9ed-433f-96d1-e24b2c7275d1)
