### ISSUE TITLE
Proxmox 8.1 and Truenas Core Problem

### ISSUE THREAD

**Issue by cundaric** [TheGrandWazoo/freenas-proxmox#182]
### Discussed in https://github.com/TheGrandWazoo/freenas-proxmox/discussions/181

<div type='discussions-op-text'>

<sup>Originally posted by **cundaric** March 21, 2024</sup>
ello,
I followed step by step the installation instructions but I'm getting the following error when trying to execute qm rescan command on Proxmox 8.1 and Truesan Core
Unable to connect to the FreeNAS API service at '192.168.20.7' using the 'https' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 380.
Plugin version
pkg -l |grep freenas
ii freenas-proxmox 2.2.0-1 all FreeNAS Plugin for Proxmox VE
line 380 "die "Unable to connect to the FreeNAS API service at '" . $apihost . "' using the '" . $scheme . "' protocol";"

IP is reachable on the port:
curl -k -I https://192.168.20.7/api/
HTTP/2 302
server: nginx
date: Thu, 21 Mar 2024 08:57:51 GMT
content-type: text/html
content-length: 138
location: https://192.168.20.7/ui/
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
permissions-policy: geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()
referrer-policy: strict-origin
x-frame-options: SAMEORIGIN

Any ideass?

</div>

**Comment by TheGrandWazoo** [comment]
TrueNAS or TrueSAN? Never heard or TrueSAN.
What version of TrueXXX are you running?
Might you have the config of your Proxmox ZFS over iSCSI?
Post syslog information of from the start to the failure.
