### ISSUE TITLE
API service at '10.20.0.1' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 389.

### ISSUE THREAD

**Issue by PBoerst** [TheGrandWazoo/freenas-proxmox#183]
I'm having this issue above, I'm not sure where to go next, I've been at this for about 25 hours.
If there is anything you need me to provide please let me know.
I also receive this when trying to delete a vm disk
()
Unable to connect to the FreeNAS API service at '10.20.0.1' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 389. (500)

**Comment by TheGrandWazoo** [comment]
What version of TrueNAS?
Might you have the config for Proxmox ZFS over iSCSI?
Post syslog info from the start to the failure.

**Comment by PBoerst** [comment]
TrueNAS-12.0-U6.1 Core
`Mar 22 13:06:01 hmlhst5 pvedaemon[123450]: <root@pam> starting task UPID:hmlhst5:0001E93F:004C32C0:65FDBA79:qmcreate:102:root@pam:
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : create_lu(/dev/zvol/ProxStore/vm-102-disk-10)
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Authentication using Bearer Token Auth
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection header Content-Type:'text/html'
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Changing to v2.0 API's
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Authentication using Bearer Token Auth
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection header Content-Type:'text/plain; charset=utf-8'
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response code: 401
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response content: 401: Unauthorized
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: VM 102 creating disks failed
Mar 22 13:06:02 hmlhst5 pvedaemon[125247]: unable to create VM 102 - Unable to connect to the FreeNAS API service at '10.20.0.1' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 389.
Mar 22 13:06:02 hmlhst5 pvedaemon[123450]: <root@pam> end task UPID:hmlhst5:0001E93F:004C32C0:65FDBA79:qmcreate:102:root@pam: unable to create VM 102 - Unable to connect to the FreeNAS API service at '10.20.0.1' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 389.
Logs
`
I noticed it says using Bearer Auth token, should it be basic as I'm using root user and pw?

**Comment by TheGrandWazoo** [comment]
What branch of the plugin are you using...testing or stable?

**Comment by PBoerst** [comment]
I believe I was using stable, but at this point I really cannot remember.

**Comment by TheGrandWazoo** [comment]
Look at your repo in Proxmox and it should tell you there.

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1273753/7c751a48-64bc-4e8f-abcf-62a2e90c0287)
In yellow is the 'testing' repo. The one above without a checkmark is 'stable'

**Comment by PBoerst** [comment]
![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/110268165/a4184006-cfb7-4a7c-9574-264d59b75e68)

Not sure how, but looks like both?

**Comment by TheGrandWazoo** [comment]
The 'testing' repo has the Bearer Token auth feature so no more User/Password is needed on newer TrueNAS version.

**Comment by TheGrandWazoo** [comment]
Only select "ONE" repo.

**Comment by PBoerst** [comment]
I'm sorry, I'm not really too sure what I should do from here to fix this.
I'm kind of a beginner at this, and learning how this all works is kind of a 2 week goal for myself.

**Comment by TheGrandWazoo** [comment]
Click on the "stable" repo and a few button will appear below "APT Repositories". One should be `disable`.
The after that is complete refresh and see if it picks up the 'testing' repo and hopefully it will have an update.

**Comment by TheGrandWazoo** [comment]
I selected the 'testing' repo on mine but this is just to show you.

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1273753/be8d8ed4-1b1b-495c-941e-816e74c5ab3f)

**Comment by TheGrandWazoo** [comment]
I'll be back. Off to my real job for awhile.

**Comment by PBoerst** [comment]
I'm trying to set this up on TrueNAS Scale now instead, most recent stable version.
I receive this `TASK ERROR: unable to create VM 102 - Undefined `freenas_user` and/or `freenas_password` variables. at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 136.`
so if I edit /etc/pve/storage.cfg, and remove 'truenas_secret' and replace it with 'freenas_password'
The error changes to this 
'Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 349.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 349.
TASK ERROR: unable to create VM 102 - Unable to connect to the FreeNAS API service at '10.20.0.1' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 389'
What am I doing wrong here?

**Comment by PBoerst** [comment]
OMG, I was following an old guide...
I'm going to have to figure out how to clean up my proxmox to start this fresh....

**Comment by TheGrandWazoo** [comment]
Send me that snip of the config in the /etc/pve/storage.cfg and, or course, remove/change
 the secret and/or ip/dns values when posting.

**Comment by PBoerst** [comment]
> Send me that snip of the config in the /etc/pve/storage.cfg and, or course, remove/change the secret and/or ip/dns values when posting.

So the Raid 1 boot drives both failed in this proxmox host last night. Brand new custom server build less than a week old. 
I picked up 2 new drives and got Truenas reinstalled for good measure and got proxmox back up on this host. 
I will be attempting this again tonight or tomorrow.
Could you link me to the most recent instructions on install? I think I followed half of 2 different things on the first install

**Comment by TheGrandWazoo** [comment]
Should be following the instructions at https://github.com/TheGrandWazoo/freenas-proxmox?tab=readme-ov-file#new-install-instructions
