### ISSUE TITLE
Feasibility for thin provisioning?

### ISSUE THREAD

**Issue by surfrock66** [TheGrandWazoo/freenas-proxmox#185]
I've been successfully using iscsi over truenas in Proxmox for some time, but am looking to expand a bit.  I'm realizing all of the zvols created for my disk are thick provisioned:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/684acd89-5d28-4425-871c-179457970bd9)

Is this a limit in how Proxmox does iscsi, or is it something that could be modified in the API calls that create the dataset?  I know in truenas when I make a zvol I can choose it to be sparse, but haven't tried it for a volume on Proxmox yet (making the volume in the nas, then trying to attach it to a vm in proxmox).  Is this something that is even possible, and if so, could it be supported in a setting in the plugin?

**Comment by TheGrandWazoo** [comment]
I will check on it. I thought there was a way but I might be mistaken.

**Comment by TheGrandWazoo** [comment]
I do see a "Thin Provisioning" checkbox. Is that not on your UI?

**Comment by surfrock66** [comment]
I see it now, I was looking in the disk config, not the iscsi lun config, my mistake.  I take it if I already made a disk, I'd have to re-create it there for it to be sparse, right?

**Comment by surfrock66** [comment]
Ok, I want to document what I did to get luns converting.

1) I had made disks on a lun created WITHOUT thin provisioning.
2) I created a new "ZFS on iSCSI" storage object this time with thin provisioning, I added the text "-thin" to the end of the name.  Everything else is identical to the first one.
3) In the VM, I go to hardware, select the disk, and do "Disk Action" -> "Move Storage"
4) I move the disk to the new -thin storage, but DO NOT check the "Delete Source" box.
5) This goes for a while and will complete.
6) The old disk will show up as "Unused Disk" in the hardware list in Proxmox.  Select it and remove it.  I don't know why, but this will fail the first time, then work the second.
7) The datastore for the old disk is going to show up in TrueNAS without an iSCSI share icon: 
![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/ca92a54f-d532-4810-8018-ee23920861ae)

8) Even though Proxmox doesn't see the datastore, it isn't gone.  To do this, first, you need to remove the extent from the iscsi share.  Be very careful to find the right one then choose "Delete" from the menu for the extent on the right:
![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/c7338f84-3d53-4ffe-a821-c7525509076a)
9) Lastly go back to the datastore and perform the delete procedure BEING VERY CAREFUL TO DELETE THE CORRECT ONE:
![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/a61f3d38-5db3-40bc-932b-7e2b5777bfe4)


When I tried to tell proxmox to delete the source, it failed, and somehow didn't unhook from TrueNAS so the datastores wouldn't delete as they were busy.  This procedure works; it's a bit annoying as my drives aren't nice orderly ID's, but they are all now showing up in TrueNAS as thin provisioned:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/b095984c-dd02-4886-a299-b68ed7373ee8)
