### ISSUE TITLE
Unable to create CT Disk

### ISSUE THREAD

**Issue by Giacomopietrafitta31** [TheGrandWazoo/freenas-proxmox#187]
Good morning everyone,

I recently discovered this tool to integrate truenas storage on proxmox. This is gorgeous!. I noticed, however, that on proxmox 8.1 it doesn't give me the ability to use container storage. The storage just doesn't appear in the creation. Anyone have any advice?

**Comment by awptechnologies** [comment]
you cant use iscsi over zfs for containers. I recommend setting up an nfs share for that if you want to use remote storage.

**Comment by TheGrandWazoo** [comment]
As stated by @awptechnologies this plugin only works with VM's in Proxmox VE.
