### ISSUE TITLE
ProxMox 8.2.2 -  Unable to find the target id for iqn...

### ISSUE THREAD

**Issue by coryarobbins** [TheGrandWazoo/freenas-proxmox#191]
Hello,

I've read several reports of people receiving messages like the following even though the disks are actually created:
`Warning: volblocksize (4096) is less than the default minimum block size (8192).
To reduce wasted space a volblocksize of 16384 is recommended.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 796.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 796.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 796.
TASK ERROR: unable to create VM 124 - Unable to find the target id for iqn.2021-07.org.wftigers.truenas at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 262.`

In most of those, the problem was a missing target configuration within TrueNAS.  I have a target, but I'm still receiving that message.  I've also tried it with a variation (adding `:proxmox` the name of my target, after the iqn), but I get the same message with the updated address.

I thought this was a compatibility issue with 8.2.2 and the latestest nightly TrueNAS Core (installed and updated today), so I installed the latest stable, and had the same issue.  I then thought it might be an issue that was also present in the stable build, so I tried to add a new VM to my existing TrueNAS setup which has NOT been updated, and HAS been working for several years, but I get the exact same error.  I just did the updates to proxmox 8 today, so it seems like the common issue is the 8.2.2 version.  

I've switched to the testing branch of freenas-proxmox, but that still doesn't resolve the issue.

Any thoughts would be greatly appreciated!

**Comment by TheGrandWazoo** [comment]
I upgraded to 8.2.4 and was not able to replicate the issue. Was this a new install or an upgrade?
