### ISSUE TITLE
No FreeNAS option

### ISSUE THREAD

**Issue by mikl0s** [TheGrandWazoo/freenas-proxmox#25]
I followed the instructions on a freshly installed and updated (with enterprise updates) Proxmox VE 5.2-9 and there is no change in the ZFS over iSCSI interface.

I also tried a different browser after a server restart to see if that would change anything.

![image](https://user-images.githubusercontent.com/7456949/47172092-cd29c300-d30a-11e8-90b7-b9439a8f7051.png)

**Comment by TheGrandWazoo** [comment]
I DO NOT have enterprise so there might be differences in the code.

Please post your output of 'pveversion -v' so I can see if the "storage" lib is different from the no-subscription branch.

**Comment by mikl0s** [comment]
`proxmox-ve: 5.2-2 (running kernel: 4.15.18-5-pve)
pve-manager: 5.2-9 (running version: 5.2-9/4b30e8f9)
pve-kernel-4.15: 5.2-8
pve-kernel-4.15.18-5-pve: 4.15.18-24
pve-kernel-4.15.17-1-pve: 4.15.17-9
corosync: 2.4.2-pve5
criu: 2.11.1-1~bpo90
glusterfs-client: 3.8.8-1
ksm-control-daemon: 1.2-2
libjs-extjs: 6.0.1-2
libpve-access-control: 5.0-8
libpve-apiclient-perl: 2.0-5
libpve-common-perl: 5.0-38
libpve-guest-common-perl: 2.0-18
libpve-http-server-perl: 2.0-11
libpve-storage-perl: 5.0-29
libqb0: 1.0.1-1
lvm2: 2.02.168-pve6
lxc-pve: 3.0.2+pve1-2
lxcfs: 3.0.2-2
novnc-pve: 1.0.0-2
proxmox-widget-toolkit: 1.0-20
pve-cluster: 5.0-30
pve-container: 2.0-27
pve-docs: 5.2-8
pve-firewall: 3.0-14
pve-firmware: 2.0-5
pve-ha-manager: 2.0-5
pve-i18n: 1.0-6
pve-libspice-server1: 0.12.8-3
pve-qemu-kvm: 2.11.2-1
pve-xtermjs: 1.0-5
qemu-server: 5.0-35
smartmontools: 6.5+svn4324-1
spiceterm: 3.0-5
vncterm: 1.5-3
zfsutils-linux: 0.7.11-pve1~bpo1`

**Comment by mikl0s** [comment]
> I DO NOT have enterprise so there might be differences in the code.
> 
> Please post your output of 'pveversion -v' so I can see if the "storage" lib is different from the no-subscription branch.
> 
> Also, I just received a machine I can use to bare-metal install the latest Proxmox VE and follow the steps above, but I will not be able to perform this task until this evening.

If you need a license let me know

**Comment by TheGrandWazoo** [comment]
Mikkel,
From looking at the patch above, I believe I forgot to add a value into an array in the pvemanagerlib.js code.
I am at a customer site right now so I don't have my development environment to create a 'patch'
If you are comfortable using an editor like 'vi' then you can fix it easy.

```vi /usr/share/pve-manager/js/pvemanagerlib.js```

Search for the word 'comstar' (without quotes) in the code it should show you something like...

```
Ext.define('PVE.form.iScsiProviderSelector', {
    extend: 'Proxmox.form.KVComboBox',
    alias: ['widget.pveiScsiProviderSelector'],
    comboItems: [
        ['comstar', 'Comstar'],
        [ 'istgt', 'istgt'],
        [ 'iet', 'IET'],
        [ 'LIO', 'LIO']
    ]
});

```

Insert a line below the ['comstar', 'Comstar'], line and add...

```
        ['freenas', 'FreeNAS-API'],
```
so it looks like this...
```
Ext.define('PVE.form.iScsiProviderSelector', {
    extend: 'Proxmox.form.KVComboBox',
    alias: ['widget.pveiScsiProviderSelector'],
    comboItems: [
        ['comstar', 'Comstar'],
        ['freenas', 'FreeNAS-API'],
        [ 'istgt', 'istgt'],
        [ 'iet', 'IET'],
        [ 'LIO', 'LIO']
    ]
});
```

Then issue the commands...
```
pvedaemon restart
pveproxy restart
```
and you should be all set until I get a fix on that patch.

If you wish to wait, I will try to get a patch uploaded tonight and post some instruction on reverting the pvemanagerlib.js to original so you can apply the new patch.

My apologies for your issues.

**Comment by mikl0s** [comment]
Yep that did it, thank you for the quick fix :)

**Comment by TheGrandWazoo** [comment]
Great. I hope everything else works underneath that fix.
Again, sorry for the issue. I am only human. Need more beer.

**Comment by mikl0s** [comment]
Unfortunately I am not experienced enough with iSCSI to figure out the FreeNAS setup and the matching PVE setup, but on paper this feature sounds amazing.

When you have time a quick example would be amazing.

**Comment by TheGrandWazoo** [comment]
Sure. I will post some screenshots in a different post for all to see. I might need to use gist.

**Comment by TheGrandWazoo** [comment]
Create an issue for the password to not be clear text. I will see how Proxmox handles that with their backend libs and hopefully find a solution.

Not sure about the second one that  the VM does not show in the Proxmox UI. Could you send screenshots please.

Thx,
Kev

**Comment by TheGrandWazoo** [comment]
> Thanks for this awesome piece of work!

I glad i found it and have been able to continue enhancing the plugin for the community.
Keep letting me know any enhancements or bugs and I will create or fix them as best I can.

Thanks,

Kev (The Grand Wazoo)

**Comment by TheGrandWazoo** [comment]
Patch uploaded in commit 7dfa7f367df960cf17fef3315146ae4560d99d9a
