### ISSUE TITLE
Update patches to latest ProxmoxVE version

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#29]
Update patch for libpve-storage-perl from 5.0-30 to 5.0-32
Update patch for pve-docs from 5.2-9 to 5.2-10
Update patch for pve-manager from 5.2-10 to 5.2-12

**Comment by mikl0s** [comment]
Any luck talking to Proxmox about adding this functionality directly into Proxmox?

**Comment by TheGrandWazoo** [comment]
I will have this issue closed out this evening (EDT) and also patches for Proxmox VE 5.3.

**Comment by TheGrandWazoo** [comment]
I do not have a system with these version of the libs running. I must of over written the system and patches. My apologies but if I remember correctly the patches before the 5.3 version worked with offsets applied automatically by the patch command.
Closing issue.
