### ISSUE TITLE
ZFS error: Unrecognized command "list_extent"

### ISSUE THREAD

**Issue by mihanson** [TheGrandWazoo/freenas-proxmox#32]
I honestly don't know if this is an issue with the FreeNAS patches (using commit 82fe272) or a problem with Proxmox, but I'm seeing the errors I outlined [here](https://forum.proxmox.com/threads/qm-unrecognized-command-list_extent.49739/) when utilizing FreeNAS as my VM storage. When performing any operation from the command line, i.e. `qm start XXX` or `qm clone XXX YYY...` I see `unrecognized command 'list_extent'` It does not seem to bother my Linux VM's that I create on the FreeNAS storage, but the VM's that I move from internal local-zfs Proxmox storage will "start," but only boot to the UEFI shell or iPXE. Moving or cloning VM's to/from the local-zfs storage does not exhibit this error, hence I think it may be relevant to these patches. Let me know if you need more information.

**Comment by TheGrandWazoo** [comment]
I noticed this also on 5.3 while migrating from a local ZFS storage to ZFS over iSCSI storage.
When I patched the 5.3 libs I used the previous patch set (for 5.2-x) and it patched fine.
The issue is see is that the only place that uses the 'zfs' command is via the SSH to get the list of ZVOL's for display in the 'content'. This is basically a fall through that if the 'list_extent' is NOT in the list of methods then it will use the 'ssh zfs <method>'. I will take a look to see 'what' changed in the ZFSPlugin.pm that might have an effect on the FreeNAS.pm plugin or something else.

Thanks,

Kev

**Comment by TheGrandWazoo** [comment]
FYI. I am assuming Proxmox VE DevOps group will probable point the finger back at this patch due to it is NOT part of their development tree.

**Comment by TheGrandWazoo** [comment]
I believe it might be because the 'list_extent' command does NOT exist in the $lun_cmds arrray in the ZFSPlugin.pm lib has shown here...
```
my $lun_cmds = {
    create_lu   => 1,
    delete_lu   => 1,
    import_lu   => 1,
    modify_lu   => 1,
    add_view    => 1,
    list_view   => 1,
    list_lu     => 1,
};
```
I will try it on me working system and see if that resolves the error. Not sure if a diff didn't catch this from previous patches.

**Comment by TheGrandWazoo** [comment]
It looks to be a regression issue with a patch. It is definily missing the list_extent index in the $lun_cmds. Quick and dirty would be to
```
vi /usr/share/perl5/PVE/Storage/ZFSPlugin.pm

insert a line between

**Comment by TheGrandWazoo** [comment]
Use 'ZFSPlugin-5.0-33_1.pm.hotfix.patch' to fix an already erred patched ZFSPlugin.pm. Remember to restart pvedaemon and pveproxy.
Otherwise use to the regular patch procedures for a fresh install or an upgraded system to 5.3.

**Comment by mihanson** [comment]
Thanks very much. I just did the quick and dirty change and the error is gone. My moved VM's still only boot to iPXE or EFI Shell, but maybe that's another issue entirely?

**Comment by TheGrandWazoo** [comment]
If you'd like just post a screenshot or what might be an error in the PVE log or tasks window, just open a new issue. I have come across when I converted to local .qcow to .raw using ZFS over iSCSI that I needed to change the cache mode of the VM driver to be 'writeback'...if I remember correctly. Worth a shot.
