### ISSUE TITLE
Unable to create disk error on line 160

### ISSUE THREAD

**Issue by bkvamme** [TheGrandWazoo/freenas-proxmox#34]
Hi, 
I am getting this error message when I try to create a new disk (clone, new vm, new disk in existing VM): 

`update VM 103: -scsi1 midgard-iscsi:1
TASK ERROR: error with cfs lock 'storage-midgard-iscsi': Unable to create lun /dev/zvol/vmtank/proxmox/disks/vm-103-disk-2 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 160.
`

`error with cfs lock 'storage-midgard-iscsi': Unable to create lun /dev/zvol/vmtank/proxmox/disks/vm-126-disk-1 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 160. at /usr/share/perl5/PVE/API2/Qemu.pm line 1253. (500)`

ssh'ing in with `ssh -i /etc/pve/priv/zfs/10.0.5.1_id_rsa -p root@10.0.5.1` works fine. 

Tested on three different Proxmox hosts, all at: 

```
Kernel Version Linux 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100)
PVE Manager Version pve-manager/5.3-6/37b3c8df
```

Patched files two days ago with the latest available from your github. 

FreeNAS 11.2-FINAL. 

Had it running earlier (prior to 11.2-FINAL update) so I currently have 6 disks running over iSCSI that was created with your patches. Not sure what broke it as I didn't notice it until now (existing disk are working fine). 

Thanks for any help!

**Comment by TheGrandWazoo** [comment]
I can not replicate you issue in my lab with FreeNAS 11.2 and Proxmox 5.3-6. Could you please post the output of your 'syslog' when creating your disk. This was my test with the parameters above and should look something like this...
```
Dec 29 10:42:49 pve pvedaemon[2604]: <root@pam> update VM 103: -virtio0 iSCSITest:32
Dec 29 10:42:49 pve pvedaemon[2604]: <root@pam> starting task UPID:pve:0000191E:029FC681:5C2795F9:qmconfig:103:root@pam:
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::lun_command : create_lu(/dev/zvol/Mirror01-128Gb/Storage01-128Gb/vm-103-disk-0)
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::API::get_globalconfig : target_basename=iqn.2018-06.com.ksatechnologies.freenas-lab.ctl
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::API::get_target() : sucessfull
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::API::get_target_to_extent() : sucessfull
Dec 29 10:42:50 pve pvedaemon[6430]: FreeNAS::API::freenas_get_first_available_lunid : return 1
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::API::get_target() : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::API::get_globalconfig : target_basename=iqn.2018-06.com.ksatechnologies.freenas-lab.ctl
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::API::get_target() : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::API::get_target_to_extent() : sucessfull
Dec 29 10:42:51 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::API::get_extent : sucessfull
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::API::freenas_list_lu : sucessfull
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::list_lu(/dev/zvol/Mirror01-128Gb/Storage01-128Gb/vm-103-disk-0):name : lun not found
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::API::get_globalconfig : target_basename=iqn.2018-06.com.ksatechnologies.freenas-lab.ctl
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::API::get_target() : sucessfull
Dec 29 10:42:52 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:53 pve pvedaemon[6430]: FreeNAS::API::create_extent(lun_path=/dev/zvol/Mirror01-128Gb/Storage01-128Gb/vm-103-disk-0) : sucessfull
Dec 29 10:42:53 pve pvedaemon[6430]: FreeNAS::api_call : setup : sucessfull
Dec 29 10:42:58 pve pvedaemon[6430]: FreeNAS::API::create_target_to_extent(target_id=1, extent_id=2, lun_id=1) : sucessfull
Dec 29 10:42:58 pve pvedaemon[6430]: FreeNAS::create_lu(lun_path=/dev/zvol/Mirror01-128Gb/Storage01-128Gb/vm-103-disk-0, lun_id=1) : sucessfull
Dec 29 10:42:58 pve pvedaemon[6430]: FreeNAS::lun_command : add_view()
Dec 29 10:42:58 pve pvedaemon[2604]: <root@pam> end task UPID:pve:0000191E:029FC681:5C2795F9:qmconfig:103:root@pam: OK
```
Except there should be some errors in the 'create_lu' area of the log.

If you don't know how to provide that just issue the following command from the shell for a realtime view...
```
tail -f /var/log/syslog
```
or to view it in edit mode to find the previous errors
```
vi /var/log/syslog
```
and search for the 'create_lun' text. Then cut and paste the entire attempt at the creation of the lun to this thread.

Thanks,

Kev

**Comment by bkvamme** [comment]
Hi, 
Feel free to close this. Appears that my FreeNAS box was having some issues. Couldn't do anything in the WebUI, kept getting an "Can't start new thread" error message, and I am guessing this would also affect your API calls. Nothing to do with this plugin. Restarted everything, and now I am able to move, create and clone disks. Thank you for your support!

**Comment by TheGrandWazoo** [comment]
Closing issue due to users request.
Seems the FreeNAS server was acting up and needed a kick.
