### ISSUE TITLE
trouble with ssh command and security consideration

### ISSUE THREAD

**Issue by provencal** [TheGrandWazoo/freenas-proxmox#35]
Hi

I found your script and it's exactly what i was looking for !

Unfortunatly i fail to run it.

I follow your instruction :

https://github.com/TheGrandWazoo/freenas-proxmox/blob/master/README.md
then i try setup the zfs over iscsi with freenas provider.

iqn.2005-10.org.freenas.ctl:scsi
![capturezfsoveriscsi](https://user-images.githubusercontent.com/3763032/50996855-63910d80-1523-11e9-8eef-e98f5ba2fc6a.PNG)

It's just an example, i try many parameter but i never found somethings working .
strangely when i try get information on content in the storage badly mounted i get this :

command '/usr/bin/ssh -o 'BatchMode=yes' -i /etc/pve/priv/zfs/10.0.0.7_id_rsa root@10.0.0.7 zfs list -o name,volsize,origin,type,refquota -t volume,filesystem -Hr' failed: exit code 255 (500)

i was thinking ssh was no more used . so what's happens ?
![capturefreenas](https://user-images.githubusercontent.com/3763032/50996867-6c81df00-1523-11e9-841f-e5b3fcc19be7.PNG)

when i try the proxmox iscsi alone it found correctly my target ... by setting 10.0.0.7 as portal.
any idee

best regards and happy new years !
----------------------------------------------------------

your email answer :
Romain,

One enhancement that I working on is to remove the dependency from SSH and use the API’s. Unfortunately it is in a backend Proxmox lib so it is taking a bit of time to create the enhancement so I don’t break other plugins. It just has to do with the listing of the contents of the ZFS pools and zols.

Please follow the steps at https://pve.proxmox.com/wiki/Storage:_ZFS_over_iSCSI that have to do with SSH between Proxmox VE and FreeNAS. The code segment should start out  ‘mkdir /etc/pve/priv/zfs’

------------------------------------------------------
next question 👍 

thanks you very much.
It's working now !

just have some questions. Actually i have done it by using root access for create keys as writed on the proxmox wiki url but is that possible to use lower security users as you looks like suggest by yourself "It just has to do with the listing of the contents of the ZFS pools and zols" ?
Really better that proxmox doesn't get root access to freenas.
Same way how use other api user account on freenas for does't set in form api username,password option with root ?
And did the option api username  is used to for the ssh user login ?

best regards,

**Comment by TheGrandWazoo** [comment]
The username and password field, at the moment, are used for two functions...ssh and api access. At the moment I have NOT tried a different username and password but if I remember the 'root' was needed for the API's when I first was getting into this. You are welcome to try and report back.

**Comment by TheGrandWazoo** [comment]
Closing due to questions answered and lack of activity on the post.
