### ISSUE TITLE
Not necessary perl5/PVE/Storage/ZFSPoolPlugin.pm file

### ISSUE THREAD

**Issue by raczkow** [TheGrandWazoo/freenas-proxmox#37]
I've noticed new file in repo: perl5/PVE/Storage/ZFSPoolPlugin.pm. Is it necessary?

**Comment by TheGrandWazoo** [comment]
Oops. My mistake. I will remove. I was trying to develop the total API version an was reverse engineering the ZFS backend and must of added it by mistake.

**Comment by TheGrandWazoo** [comment]
Uploaded fix 2f22e6062682b12a26634c85927ff4efeff7abc4 to repo
