### ISSUE TITLE
Multipath howto?

### ISSUE THREAD

**Issue by ZS-Man** [TheGrandWazoo/freenas-proxmox#39]
Hi, is there any documentation about using/configuring multipath with this ZFS over ISCSI plugin?

Thanks.

**Comment by TheGrandWazoo** [comment]
I do not have any and I do not use the multipath option. It was developed by another follower of the project. I will see what I can dig up.

**Comment by jrdeck** [comment]
Just saw this. We can probably put  together a HOWTO. In the meantime, though, here is an excerpt from our internal docs:

Log into the UI of Proxmox and check if you are able to add a FreeNAS iSCSI storage array LUN. The basic setup should be complete prior to adding additional iSCSI interfaces. 


Now you need to edit or create the iscsi configuration file /etc/iscsi/iscsid.conf

    node.startup = automatic
    node.session.timeo.replacement_timeout = 15

Then do a restart of the iSCSI daemon to load the new config

    systemctl restart iscsid

To ensure that multipath is available install multipath-tools
    
    apt-get install multipath-tools

Edit or create if required the file /etc/multipath.conf and add the following to the file

    defaults {
            polling_interval        2
            path_selector           "round-robin 0"
            path_grouping_policy    multibus
            uid_attribute           ID_SERIAL
            rr_min_io               100
            failback                immediate
            no_path_retry           queue
            user_friendly_names     yes
    }
    
And then restart the multipath service

    service multipath-tools restart

**CRITICAL STEP** run the following from each host to ensure that iscsi client is able to see the iscsi host. If this is not done then strange issues with Storage may occur. Diagnosis below

    iscsiadm -m discovery -t st -p 10.20.20.110
    iscsiadm -m node -—login

**Comment by goberreuter** [comment]
Hi guys, interesting project! Been struggling as of late, as to how to configure proxmox ve with freenas over iscsi, this plugin seems to be it!
I got a FreeNAS server with 10G interfaces, and the zvol targets exposed using iscsi.
I am interested as well in the multipath option. Got it already working, and as for now, configured LVM on top of it. So far so good. But miss the snapshots functionality.

Question: if i got the multipath working, and after that make use of this plugin, can I expect to get zfs over iscsi working with multipath? Because the proxmox ve post about zfs over iscsi indicates that multipath is still not working (https://pve.proxmox.com/wiki/Storage:_ZFS_over_iSCSI).
Thanks

**Comment by jrdeck** [comment]
> can I expect to get zfs over iscsi working with multipath?

Yes. 

Kind Regards,
James Deck
Director
Clevvi - Formerly 1300 Web Pro
p1300 932 776
ejdeck@clevvi.com.au
wclevvi.com.au
aUnit 22, 489 South Street, Toowoomba 4350
Unit 14, 17 Karp Court, Bundall 4217
Need help?
LOG A JOB ONLINE
Feed your brain
WATCH OUR WEBCHATS
Click here to leave a review on Google

**Comment by goberreuter** [comment]
Thanks.

I was able to setup ZFS over iSCSI: the 3 nodes of my cluster have access to the storage.
I tried to move a harddrive of one of the VM to the new zfs over iscsi storage, and got the following:

`create full clone of drive ide0 (san-x3650m5-hdd:vm-101-disk-0)
Use of uninitialized value $target_id in numeric eq (==) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 508.
TASK ERROR: storage migration failed: error with cfs lock 'storage-san-x3650m5-ssd': Unable to find the target id for 3650.target.all at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.`

multipath -ll output
`root@dc-pmontt-flex-nodo02:/# multipath -ll
mpath0 (36589cfc000000d68e17c6b320cb68bde) dm-5 FreeNAS,iSCSI Disk
size=4.0T features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
`-+- policy='round-robin 0' prio=50 status=active
  |- 4:0:0:30 sdc 8:32 active ready running
  `- 5:0:0:30 sdd 8:48 active ready running`

followed the indications: setup ssh keys, validated ssh login working, applied the patches and so on, the cluster aparently is OK with the newly added storage.

Any ideas?
Thanks

**Comment by Uplink-snafu** [comment]
@goberreuter  would you mind documenting how you were able to get MPIO (and I assume, ALUA) to work?

I've been struggling getting MPIO to work with a TrueNAS HA unit for the better part of 2 days

**Comment by TheGrandWazoo** [comment]
Please see Issue #88. This may help you with the setup.

**Comment by goberreuter** [comment]
> @goberreuter would you mind documenting how you were able to get MPIO (and I assume, ALUA) to work?
> 
> I've been struggling getting MPIO to work with a TrueNAS HA unit for the better part of 2 days

I switched to a configuration where zfs is not being used over iscsi, and I did not document the procedure in a clean way (it was trial and error, mostly). Reading the documentation of multipath on linux got me there, good luck!
