### ISSUE TITLE
Error while attempting to rollback linked clone

### ISSUE THREAD

**Issue by keslerm** [TheGrandWazoo/freenas-proxmox#42]
An error is generated when trying to rollback a linked clone from a template. I get the following error:

```
Could not find lu_name for zvol base-9000-disk-0/vm-119-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 116.
```

119 is the clone, 9000 is the template.

I tested it with a full clone and it works fine.

I'll probably poke around the code for this but I'm going to report it in case someone else gets it/has gotten it.

**Comment by TheGrandWazoo** [comment]
If possible, could you post the snip in syslog when doing the rollback. I send a lot a info there and might give me an idea of what if going on...from the FreeNAS.pm plugin.

**Comment by keslerm** [comment]
Sure

```
Jul 11 08:55:39 enterprise pvedaemon[13316]: FreeNAS::lun_command : list_lu(/dev/zvol/base-9000-disk-0/vm-119-disk-0)
Jul 11 08:55:39 enterprise pvedaemon[13316]: FreeNAS::api_call : setup : sucessfull
Jul 11 08:55:39 enterprise pvedaemon[13316]: FreeNAS::API::get_target() : sucessfull
Jul 11 08:55:39 enterprise pvedaemon[13316]: FreeNAS::api_call : setup : sucessfull
Jul 11 08:55:39 enterprise pvedaemon[13316]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Jul 11 08:55:39 enterprise pvedaemon[13316]: FreeNAS::api_call : setup : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::API::get_target() : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::api_call : setup : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::API::get_target_to_extent() : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::api_call : setup : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::API::get_extent : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::API::freenas_list_lu : sucessfull
Jul 11 08:55:40 enterprise pvedaemon[13316]: FreeNAS::list_lu(/dev/zvol/base-9000-disk-0/vm-119-disk-0):name : lun not found
Jul 11 08:55:40 enterprise pvedaemon[13316]: Could not find lu_name for zvol base-9000-disk-0/vm-119-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 116.
Jul 11 08:55:40 enterprise pvedaemon[25695]: <root@pam> end task UPID:enterprise:00003404:02E1FDBF:5D2731CB:qmrollback:119:root@pam: Could not find lu_name for zvol base-9000-disk-0/vm-119-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 116.
```

**Comment by TheGrandWazoo** [comment]
If possible, could you post the snip in syslog when doing the rollback. I send a lot a info there and might give me an idea of what if going on...from the FreeNAS.pm plugin.

**Comment by TheGrandWazoo** [comment]
Will be looking at this in the lab. I have a few larger SSD drives so I can try to replicate this. I have NOT done this scenario so I need to see if what the diff is between plain clones and template clones.

**Comment by TheGrandWazoo** [comment]
I am sorry. I can not replicate this. I have created a template and did a Linked Clone (very cool by the way) and got it running. But I can't find out how to "Roll Back" to the original template. It does not provide me with that option. If you could provide some screenshots of this I would be grateful.

**Comment by TheGrandWazoo** [comment]
I have not been able to replicate the issue and have not heard any additional comments one this.
Please reopen if you are still having issues and maybe we can somehow figure out what is different on your setup.
