### ISSUE TITLE
Update for 6.0-5

### ISSUE THREAD

**Issue by TheUdK** [TheGrandWazoo/freenas-proxmox#45]
Hi

Could you update for 6.0-5 if possible. Would greatly appreciate.

Look like they changed ZFSPlugin.pm

Getting this error on VM Start
`task started by HA resource agent
TASK ERROR: freenas: unknown iscsi provider. Available [comstar, istgt, iet, LIO] at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 35.`

This is the output of the ZFSPlugin.pm patch
```patching file /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
Hunk #1 succeeded at 10 with fuzz 1.
Hunk #2 FAILED at 27.
Hunk #3 succeeded at 40 (offset -1 lines).
Hunk #4 succeeded at 62 (offset -3 lines).
Hunk #5 succeeded at 160 (offset -5 lines).
Hunk #6 succeeded at 187 (offset -5 lines).
Hunk #7 FAILED at 237.
Hunk #8 succeeded at 258 (offset -11 lines).
2 out of 8 hunks FAILED -- saving rejects to file /usr/share/perl5/PVE/Storage/ZFSPlugin.pm.rej
```

Regards
UdK

**Comment by TheGrandWazoo** [comment]
Will do. It is on my list for this weekend to update my lab to 6.0 and then the FreeNAS Plugin.

Thanks for you continued support.

**Comment by TheGrandWazoo** [comment]
Maybe will try to get it pushed out tonight. Bear with me.

**Comment by TheUdK** [comment]
No worries. Take your time. Its only on test env.

No reason to thank me. Im the one thanking you for the plugin.

**Comment by TheGrandWazoo** [comment]
Ok. What I will do it create the last patch for 5.x and branch (Head) it and 6.x will continue to be the "MASTER".

Thank you. Glad everyone is getting benefits from it.

**Comment by TheGrandWazoo** [comment]
Currently upgrading my lab Proxmox VE to 6.0. Will be providing patches shortly for PVE 6.0

**Comment by TheGrandWazoo** [comment]
I have applied the patches that I created with the 5.4-13 Proxmox VE to the 6.0-5 version with no issues except some offsets notifications. Could you display the output of your 
```
pveversion -v
```
and post it here?

**Comment by TheUdK** [comment]
```
proxmox-ve: 6.0-2 (running kernel: 5.0.18-1-pve)
pve-manager: 6.0-5 (running version: 6.0-5/f8a710d7)
pve-kernel-5.0: 6.0-6
pve-kernel-helper: 6.0-6
pve-kernel-5.0.18-1-pve: 5.0.18-1
pve-kernel-5.0.15-1-pve: 5.0.15-1
ceph-fuse: 12.2.11+dfsg1-2.1
corosync: 3.0.2-pve2
criu: 3.11-3
glusterfs-client: 5.5-3
ksm-control-daemon: 1.3-1
libjs-extjs: 6.0.1-10
libknet1: 1.10-pve1
libpve-access-control: 6.0-2
libpve-apiclient-perl: 3.0-2
libpve-common-perl: 6.0-3
libpve-guest-common-perl: 3.0-1
libpve-http-server-perl: 3.0-2
libpve-storage-perl: 6.0-6
libqb0: 1.0.5-1
lvm2: 2.03.02-pve3
lxc-pve: 3.1.0-61
lxcfs: 3.0.3-pve60
novnc-pve: 1.0.0-60
proxmox-mini-journalreader: 1.1-1
proxmox-widget-toolkit: 2.0-5
pve-cluster: 6.0-4
pve-container: 3.0-5
pve-docs: 6.0-4
pve-edk2-firmware: 2.20190614-1
pve-firewall: 4.0-6
pve-firmware: 3.0-2
pve-ha-manager: 3.0-2
pve-i18n: 2.0-2
pve-qemu-kvm: 4.0.0-3
pve-xtermjs: 3.13.2-1
qemu-server: 6.0-7
smartmontools: 7.0-pve2
spiceterm: 3.1-1
vncterm: 1.6-1
zfsutils-linux: 0.8.1-pve1
```

**Comment by TheUdK** [comment]
After further testing your latest build works on my version. It took a reboot of all three cluster members before i could boot guests in HA. Do you test on a cluster? I guess you might be missing a service to restart on a HA cluster.

**Comment by TheGrandWazoo** [comment]
I do test in a single and cluster environments. I do NO have any HA setup.

**Comment by TheGrandWazoo** [comment]
Patches updated to the latest Proxmox VE as stated in the commit message.
