### ISSUE TITLE
Automatic Periodic Snapshots

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#46]
Wondering if there is an interest to have periodic snapshots available from the Proxmox VE GUI when FreeNAS is selected. After some testing I noticed that the periodic snapshots on the FreeNAS can NOT be rolled back seemingly due to the Proxmox VE holding on to the iSCSI target. But you can rollback a Proxmox VE Snapshot so I am assuming Proxmox VE backend does some magic to make that happen.

Community's thoughts?

**Comment by tl8roy** [comment]
Considering Snapshots were a part of our backup strategy (though probably more of a rebuild type scenario), this would be good to have.

**Comment by swk** [comment]
What Tristan said

**Comment by tl8roy** [comment]
So for various reasons, we tested this in the wild accidentally.

Our notes:

- In FreeNAS UI, remove all snapshots taken by FreeNAS after the Proxmox snapshot
- Conduct roll back in Proxmox UI

**Comment by tl8roy** [comment]
So we might have done some of the work in getting the technical steps worked out: https://serverfault.com/questions/980803/how-attach-existing-zfs-disk-to-proxmox-vm/980804

 An important note: a cloned FreeNAS snapshot (and Proxmox Snapshot) doesn’t replicate properly. Hence the hold is important if it needs to be redone on the replicated NAS.

**Comment by yaroslav-gwit** [comment]
I am using this solution to do automatic snaps.
https://github.com/Corsinvest/cv4pve-autosnap

Would be great if there was a GUI option inside ProxMox, but cv4pve-autosnap is robust and overall good enough as is for the time being.

**Comment by franklupo** [comment]
> I am using this solution to do automatic snaps.
> https://github.com/Corsinvest/cv4pve-autosnap
> 
> Would be great if there was a GUI option inside ProxMox, but cv4pve-autosnap is robust and overall good enough as is for the time being.

HI,
the graphical WebUi toolbox see cv4pve-tools.com. Autosnap and more

**Comment by TheGrandWazoo** [comment]
@yaroslav-gwit, @franklupo - Thank you for your comments.
I am looking at pulling the FreeNAS Lun based plugin out and creating a "FreeNAS-ZFS" plugin under /usr/perl5/PVE/Storage/Custom. The Proxmox VE Storage.pm module actually looks for modules in this directory and loads them in. Yes the GUI will still need to be "patched" to the Proxmox VE docs api but I am going to look at the cv4pve-tools to see what they do for GUI plugin.
Will will decouple the FreeNAS from the backend ZFS modules and allow a true FreeNAS API based plugin.
