### ISSUE TITLE
Push the code upstream

### ISSUE THREAD

**Issue by dani** [TheGrandWazoo/freenas-proxmox#47]
Just tried on a test VM, and everything seems to be working as expected. Thanks for your work on this !
Now, I'm a bit reluctant to start relying on this as long as it's not upstream, have you tried to push this upstream already ? Any blocker for it to be merged ?

**Comment by swk** [comment]
would love to see this upstreamed but who knows if they’ll actually incorporate it. still, running in production with dual fnas storage nodes and 12 pmox ve nodes

**Comment by TheGrandWazoo** [comment]
Thanks. I will see if I can clone their git repo and see if they will except my changes.
In the mean time, I am developing a deb package that will do all that is mentioned in the README except the SSH keys. So if a new pve-manager is loaded the package will apply the patch to just pve-manager. I currently have an alpha version of the deb package and expect sometime this week to actually get it on a deb repo server so you can add the repo and apt install it to your systems.

Thanks for everyone support.

**Comment by TheGrandWazoo** [comment]
I have posted a WIKI page on the about the repo and how to get started using it.

[https://github.com/TheGrandWazoo/freenas-proxmox/wiki/Using-the-KSA-Technologies-Debian-Repo---BETA]

**Comment by lion24** [comment]
Hi,

Any news about getting this upstream ?
To be honest, I'm also not really reluctant to modify my ProxmoxVE server core with non upstream code for reliability questions...

Anyway, great work! It seems to be a nice addition that Proxmox should have.

Cheers.

Lionel.

**Comment by Ramblurr** [comment]
Would love to see this upstreamed too.

Did you see that back in January what the Proxmox staff had to say? https://forum.proxmox.com/threads/ctld-support-for-zfs-over-iscsi.29811/post-290895

**Comment by lion24** [comment]
> Would love to see this upstreamed too.
> 
> Did you see that back in January what the Proxmox staff had to say? https://forum.proxmox.com/threads/ctld-support-for-zfs-over-iscsi.29811/post-290895

Oh, so basically the patch are there waiting for inclusion... Mmmh but it seems the author of the changeset does not care anymore..

**Comment by swk** [comment]
@TheGrandWazoo Hey I would be more than happy to assist in getting this shaped up into a proper PR for upstream if that would help you out. would still love to see that happen.

**Comment by TheGrandWazoo** [comment]
Hello all. I have recently come into employment after a long, long journey during the past year. So, have have been a bit busy onboarding to the new job.
I am committed (I thought) to this project as best I can, but it does not pay the bills.
I would love to see the plugin in the upstream code, but I have seen other code pushed upstream that has NOT made it into the code base (Look at the Proxmox Git for some).
Now, I would like to make it it's own module and NOT off the ZFSPlugin.pm so the module has more control over errors.

Let me know what you think. If you want me to submit it as is..let me know.

**Comment by swk** [comment]
Hey @TheGrandWazoo! I dont think anyone is saying abandon it to up stream. As a ling term open source contributor, I think what we are suggesting is getting this mainlined will help reduce some of the support headaches and will reduce some of your workload in upgrades because something changed in mainline.

Typically when they bring patches, the person making a new patch has to ensure that what they are doing doesnt break things. At the very least you know about it way early in the dev cycle so you can assist or say hey this is gonna break my feature. Dont do it that way, do it this way.

This also leads to a better over all user experience and ads to your resume of work. Sure you wont be a top contributor but that opens more doors for you. 

The down side is giving up some control over the patch once it goes in. This might not be such a bad thing tho.

Keep up the good work and i hope the new job works out well for you!

Ken

**Comment by TheGrandWazoo** [comment]
Hi @swk (Ken), I have no problems issuing a pull request to the Proxmox Github master. I just don't want it to sit there and not get added to the mainstream code.
I have no issues helping out with debugging or maintaining that plugin itself...I believe it can be better.
I will make an attempt to clone, create a feature branch and then a pull request for the plugin during the next week.

Thanks for all of your support and I hope you found value in this project.

Things I think I want to add include/improve:
A multipath GUI and install.
FreeNAS/TrueNAs being a separate module, not a LunCmd plugin.
Separate GUI for FreeNAS. More control.

Just throwing ideas out there from open issues and questions that arise.

Kevin
