### ISSUE TITLE
Multipath issue in FreeNAS.pm

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#48]
Thanks.

I was able to setup ZFS over iSCSI: the 3 nodes of my cluster have access to the storage.
I tried to move a harddrive of one of the VM to the new zfs over iscsi storage, and got the following:

`create full clone of drive ide0 (san-x3650m5-hdd:vm-101-disk-0)
Use of uninitialized value $target_id in numeric eq (==) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 508.
TASK ERROR: storage migration failed: error with cfs lock 'storage-san-x3650m5-ssd': Unable to find the target id for 3650.target.all at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.`

multipath -ll output
`root@dc-pmontt-flex-nodo02:/# multipath -ll
mpath0 (36589cfc000000d68e17c6b320cb68bde) dm-5 FreeNAS,iSCSI Disk
size=4.0T features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
`-+- policy='round-robin 0' prio=50 status=active
  |- 4:0:0:30 sdc 8:32 active ready running
  `- 5:0:0:30 sdd 8:48 active ready running`

followed the indications: setup ssh keys, validated ssh login working, applied the patches and so on, the cluster aparently is OK with the newly added storage.

Any ideas?
Thanks

edit: using:
`Kernel Version Linux 5.0.18-1-pve #1 SMP PVE 5.0.18-2 (Fri, 2 Aug 2019 14:51:00 +0200)
PVE Manager Version pve-manager/6.0-5/f8a710d7`

_Originally posted by @goberreuter in https://github.com/TheGrandWazoo/freenas-proxmox/issues/39#issuecomment-521302848_

**Comment by TheGrandWazoo** [comment]
I do not have a multipath setup, I use LACP in my lab environment. Would it be possible to get the syslog snip of this and post it here?

**Comment by goberreuter** [comment]
Attaching the following:
- screenshot trying to move the disk in proxmox gui
- screenshot of the failure reported in GUI
- snip of syslog when this happen

Also:
- the zvol is created OK at FreeNAS side
- proxmox cannot make use of it
- then, if I try to remove the zvol from proxmox GUI, in the zfs over iscsi storage, a validation stating that a VM with id 101 exists, prevents the disk deletion
- as this zvol is effectively not in use, I just remove it in FreeNAS
- perhaps the validation of the removal should consider if the disk is in fact in use by a VM

Let me know of any way I can help you tackle this situation.

Thanks!

> Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.238695] sd 5:0:0:31: [sdf] Sense Key : Illegal Request [current]
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.238696] sd 5:0:0:31: [sdf] Add. Sense: Logical unit not supported
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.238929] sd 5:0:0:31: [sdf] Read Capacity(10) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.238930] sd 5:0:0:31: [sdf] Sense Key : Illegal Request [current]
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.238932] sd 5:0:0:31: [sdf] Add. Sense: Logical unit not supported
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.242139] sd 4:0:0:31: alua: rtpg failed
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.242540] sd 4:0:0:31: [alua] Sense Key : Illegal Request [current]
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.242541] sd 4:0:0:31: [alua] Add. Sense: Logical unit not supported
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.242547] sd 4:0:0:30: alua: port group 01 state A non-preferred supports TolUSNA
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.250136] sd 5:0:0:31: alua: rtpg failed
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.250333] sd 5:0:0:31: [alua] Sense Key : Illegal Request [current]
Aug 16 11:46:44 dc-pmontt-flex-nodo02 kernel: [328815.250334] sd 5:0:0:31: [alua] Add. Sense: Logical unit not supported
Aug 16 11:47:00 dc-pmontt-flex-nodo02 systemd[1]: Starting Proxmox VE replication runner...
Aug 16 11:47:01 dc-pmontt-flex-nodo02 systemd[1]: pvesr.service: Succeeded.
Aug 16 11:47:01 dc-pmontt-flex-nodo02 systemd[1]: Started Proxmox VE replication runner.
Aug 16 11:47:01 dc-pmontt-flex-nodo02 pvedaemon[47708]: <root@pam> move disk VM 101: move --disk ide0 --storage san-x3650m5-ssd
Aug 16 11:47:01 dc-pmontt-flex-nodo02 pvedaemon[47708]: <root@pam> starting task UPID:dc-pmontt-flex-nodo02:0000B4AD:01F5C181:5D56CFF5:qmmove:101:root@pam:
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::lun_command : create_lu(/dev/zvol/SSD_RAID10/vm-101-disk-0)
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_target() : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_target_to_extent() : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: Use of uninitialized value $target_id in numeric eq (==) at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 508.
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::freenas_get_first_available_lunid : return 0
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_target() : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_target() : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::freenas_list_lu : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::list_lu(/dev/zvol/SSD_RAID10/vm-101-disk-0):name : lun not found
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::api_call : setup : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: FreeNAS::API::get_target() : sucessfull
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[46253]: storage migration failed: error with cfs lock 'storage-san-x3650m5-ssd': Unable to find the target id for 3650.target.all at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.
Aug 16 11:47:02 dc-pmontt-flex-nodo02 pvedaemon[47708]: <root@pam> end task UPID:dc-pmontt-flex-nodo02:0000B4AD:01F5C181:5D56CFF5:qmmove:101:root@pam: storage migration failed: error with cfs lock 'storage-san-x3650m5-ssd': Unable to find the target id for 3650.target.all at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.625294] sd 4:0:0:30: alua: supports implicit TPGS
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.625299] sd 4:0:0:30: alua: device t10.FreeNAS iSCSI Disk      0894ef03d54800                  port group 1 rel port 3
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.626724] sd 4:0:0:31: alua: supports implicit TPGS
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.626726] sd 4:0:0:31: alua: No device descriptors found
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.626727] sd 4:0:0:31: alua: port group 1 rel port 3
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627009] sd 4:0:0:31: [sde] Unit Not Ready
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627011] sd 4:0:0:31: [sde] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627013] sd 4:0:0:31: [sde] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627243] sd 4:0:0:31: [sde] Read Capacity(16) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627244] sd 4:0:0:31: [sde] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627247] sd 4:0:0:31: [sde] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627489] sd 4:0:0:31: [sde] Read Capacity(10) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627490] sd 4:0:0:31: [sde] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.627491] sd 4:0:0:31: [sde] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.634222] sd 4:0:0:30: alua: port group 01 state A non-preferred supports TolUSNA
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.636065] sd 5:0:0:30: alua: supports implicit TPGS
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.636069] sd 5:0:0:30: alua: device t10.FreeNAS iSCSI Disk      0894ef03d54800                  port group 1 rel port 3
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637514] sd 5:0:0:31: alua: supports implicit TPGS
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637516] sd 5:0:0:31: alua: No device descriptors found
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637517] sd 5:0:0:31: alua: port group 1 rel port 3
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637725] sd 5:0:0:31: [sdf] Unit Not Ready
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637726] sd 5:0:0:31: [sdf] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637728] sd 5:0:0:31: [sdf] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637961] sd 5:0:0:31: [sdf] Read Capacity(16) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637962] sd 5:0:0:31: [sdf] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.637963] sd 5:0:0:31: [sdf] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.638218] sd 4:0:0:31: alua: rtpg failed
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.638221] sd 5:0:0:31: [sdf] Read Capacity(10) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.638594] sd 5:0:0:31: [sdf] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.638595] sd 4:0:0:31: [alua] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.638596] sd 4:0:0:31: [alua] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.638597] sd 5:0:0:31: [sdf] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.650261] sd 5:0:0:31: alua: rtpg failed
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.650263] sd 5:0:0:31: [alua] Sense Key : Illegal Request [current]
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.650265] sd 5:0:0:31: [alua] Add. Sense: Logical unit not supported
Aug 16 11:47:05 dc-pmontt-flex-nodo02 kernel: [328835.650354] sd 5:0:0:30: alua: port group 01 state A non-preferred supports TolUSNA
root@dc-pmontt-flex-nodo02:/var/log#


<a href="https://ibb.co/zxhng1Q"><img src="https://i.ibb.co/zxhng1Q/cannot-remove.png" alt="cannot-remove" border="0"></a> 

<a href="https://ibb.co/hCMwwGD"><img src="https://i.ibb.co/hCMwwGD/cannot-remove02.png" alt="cannot-remove02" border="0"></a> 

<a href="https://ibb.co/dPzRNDq"><img src="https://i.ibb.co/dPzRNDq/trying-to-move-disk.png" alt="trying-to-move-disk" border="0"></a> 

<a href="https://ibb.co/dWbp1nr"><img src="https://i.ibb.co/dWbp1nr/trying-to-move-disk02.png" alt="trying-to-move-disk02" border="0"></a>

**Comment by TheGrandWazoo** [comment]
@goberreuter - Sorry I am just looking at this since I have some downtime.
Are you still having issues with this?
If so could you provide the following...
Your ZFS over iSCSI screenshot on the GUI or storage.cfg to FreeNAS.
The output of http://<your FreeNAS System IP or Name>/api/v1.0/services/iscsi/target/?limit=0

Seems to be missing the target name from the API call.

If not what we the issue?

**Comment by dusatvoj** [comment]
Hi, any progress here? I want to use `ZFS over iSCSI` with freenas and mutlipath.

**Comment by TheGrandWazoo** [comment]
I am currently just trying to understand Multipath and make a secondary Proxmox VE box to my FreeNAS box that just does Multipathing.

I am also creating a GUI plugin for Proxmox VE to configure iSCSI Multipathing. I am not sure weather to include it with this project or its own project.

Comments are welcome.

**Comment by TheGrandWazoo** [comment]
I have some other users using the multi-path option of the Proxmox VE. You must manually configure it and the Proxmox VE site has a page on how to do that...
https://pve.proxmox.com/wiki/ISCSI_Multipath

Plus look at Issue #39 that shows the users notes on how they configured it.

Also, the new updates to use the API's might have fixed this issues due to some changes that happened since FreeNAS 11.2-U5 which we needed to start using the v2.0 API of FreeNAS.
