### ISSUE TITLE
Resizing online doesn't fully work

### ISSUE THREAD

**Issue by dani** [TheGrandWazoo/freenas-proxmox#49]
When resizing a disk of an online guest, the zvol itself is correctly resized, but the guest isn't notified about the new size.

I'm testing with VirtIO SCSI disk on CentOS 7 guest. When using an LVM thin storage, just after a resize, I see in logs :

```
août 20 12:39:37 localhost.localdomain kernel: sd 2:0:0:1: Capacity data has changed
août 20 12:39:37 localhost.localdomain kernel: sd 2:0:0:1: [sdb] 6365184 512-byte logical blocks: (3.25 GB/3.03 GiB)
août 20 12:39:37 localhost.localdomain kernel: sdb: detected capacity change from 3246391296 to 3258974208
```

When doing exactly the same with ZFS over iSCSI with FreeNAS API, I get 
```
août 20 12:43:30 localhost.localdomain kernel: sd 2:0:0:0: Warning! Received an indication that the LUN assignments on this target have changed. The Linux SCSI layer does not automatical
```

And the disk still has the previous size. I either need to reboot, or rescan with : 
```
echo 1 > /sys/class/block/sdb/device/rescan
```

It seems strange that both storages doesn't behave the same from the guest POV.

**Comment by dani** [comment]
Indeed, might be a problem is qemu. I can reproduce the same issue with ZFS over iSCSI on a Linux box (using the LIO provider in proxmox, after patching as resize doesn't work at all in the stock LIO plugin)

**Comment by TheGrandWazoo** [comment]
Using FreeNAS 11.3-U3.2, Proxmox 6.2-6 and the latest freenas-proxmox plugin I was able to resize a running CentOS 8 ZFS over iSCSI 32Gb disk by 8Gb to 40Gb via the GUI. FreeNAS, Proxmox VE and CentOS 8 ALL noticed the change without issues.
