### ISSUE TITLE
Proposing a new feature

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#52]
Well in talking to the FreeNAS developers on what is happening with the issue of a zvol being deleted where it be in a move, delete or other means from the Proxmox side.
I am wondering if I should had a feature to "Create" a target for each VM. It would be a check box that would either parse/select/create a Single Target per VM or use the target under the global Target field.

FreeNAS is also adding a feature to "force"  the deletion of the zvol if the target is "In Use" but that is not due to 11.3_1/2.

What do you y'all think?

**Comment by TheGrandWazoo** [comment]
Also, a user has ask the Proxmox team to have this as part of the mainstream code. Are you guys OK with that. I am fine with it. If I need to test a feature/bugs I'm not sure if 'patches' will still work

**Comment by tl8roy** [comment]
We are fine with it being up-streamed to Proxmox.
I have noticed that we have a lot of zvols that should have been deleted, but have not been.
Restoring previously created targets is something that our recovery plan doesn't cover. Having an option in the UI would be good.

**Comment by askeveryman** [comment]
Absolutely fine with this being up-streamed.

As for deletes: they're a bit of a problem when something goes wrong and the target extent is created but the LUN isn't.  They have to be done manually (right now) from the FreeNAS side as Proxmox doesn't allow deletion of a target when there's a matching VM -- even though there's NO matching LUN.  I see this as a more general Proxmox issue and not FreeNAS-specific.  It's a one-size-mostly-fits-all check in a place where overdiagnosis of a storage volume as "in use" is preferable to misdiagnosis as not.  It's not a big issue for me as our clusters are quite small -- 3-4 nodes with no more than a half-dozen VMs each.
