### ISSUE TITLE
Do you have to patch each node in a cluster?

### ISSUE THREAD

**Issue by qome** [TheGrandWazoo/freenas-proxmox#53]
Do you have to perform the instruction steps for each node in a cluster? Is it good enough to perform the steps on the master node?

**Comment by qome** [comment]
It looks like you do have to SSH into FreeNAS on each node. I don't know about the other steps.

**Comment by TheGrandWazoo** [comment]
Yes, you have to patches and do the ssh tasks on each node of the cluster.

**Comment by TheGrandWazoo** [comment]
Or read the WIKI to find out how to do it automatically via a repo.

FYI, the current repo is a test repo, I will be changing to a development and production repo in the near future.
Also, looking at placing this in the mainstream code of Proxmox.

**Comment by qome** [comment]
You got it. I found out just now I had to patch them because in the event of a failure the other nodes won't understand the configuration, so I came back here to report and look up the configuration again.
