### ISSUE TITLE
Automatic failover: unkown iscsi provider. 

### ISSUE THREAD

**Issue by Fernien** [TheGrandWazoo/freenas-proxmox#55]
Hey,

i've run into an issue when i tried automatic failover for virtual machines in my Proxmox cluster. 
I followed your guide and can create and also live migrate machines to and from every note but when i unplugged the Ethernet cable to simulate a dead note i run into the following issue:
` root@pam: freenas: unknown iscsi provider. Available [comstar, istgt, iet, LIO] at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 35.`

I used 3 Machines to do the failover test. The zfs over iscsi one didnt make it, the nfs one which is on the same freenas system as the zfs one survived the failover as well as the one on the ceph.

Currently using:
- Proxmox 6.1-7
- FreeNAS 11.3

Not sure which logs could help there. Thanks in advance and if there is any missing information i'll provide them asap.

**Comment by TheGrandWazoo** [comment]
Well from the looks of it the patch to /usr/share/perl5/PVE/Storage/ZFSPlugin.pm did not get applied. Check that file for ANY 'freenas' entries. If none then just apply the patch. Then run the 'systemctl' commands.

Did you use the README.md procedure or the WIKI repo procedure? Did you run or apply the patches to each Proxmox node?

K

**Comment by Fernien** [comment]
That was the first thing i thought off as well. I double checked each of my 3 nodes and double checked everything.



I used the README.md and did this on every node:
apt-get install librest-client-perl git

git clone https://github.com/TheGrandWazoo/freenas-proxmox.git

cd /root/freenas-proxmox
patch -b /usr/share/pve-manager/js/pvemanagerlib.js < pve-manager/js/pvemanagerlib.js.patch
patch -b /usr/share/perl5/PVE/Storage/ZFSPlugin.pm < perl5/PVE/Storage/ZFSPlugin.pm.patch
patch -b /usr/share/pve-docs/api-viewer/apidoc.js < pve-docs/api-viewer/apidoc.js.patch


cp perl5/PVE/Storage/LunCmd/FreeNAS.pm /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm

systemctl restart pvedaemon
systemctl restart pveproxy
systemctl restart pvestatd


I generated the ssh-key and logged in from each node to the freenas. I don't think its because the patches are not applied because i can create a vm from every node using zfs over iscsi.


```
root@tick:~# grep freenas /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
    die "$provider: unknown iscsi provider. Available [comstar, freenas, istgt, iet, LIO]";
    } elsif ($scfg->{iscsiprovider} eq 'freenas') {
        } elsif ($scfg->{iscsiprovider} eq 'freenas') {
	freenas_user => {
	freenas_password => {
	freenas_use_ssl => {
	freenas_apiv4_host => {
	freenas_user => { optional => 1 },
	freenas_password => { optional => 1 },
	freenas_use_ssl => { optional => 1 },
	freenas_apiv4_host => { optional => 1 },

root@trick:~# grep freenas /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
    die "$provider: unknown iscsi provider. Available [comstar, freenas, istgt, iet, LIO]";
    } elsif ($scfg->{iscsiprovider} eq 'freenas') {
        } elsif ($scfg->{iscsiprovider} eq 'freenas') {
	freenas_user => {
	freenas_password => {
	freenas_use_ssl => {
	freenas_apiv4_host => {
	freenas_user => { optional => 1 },
	freenas_password => { optional => 1 },
	freenas_use_ssl => { optional => 1 },
	freenas_apiv4_host => { optional => 1 },

root@track:~# grep freenas /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
    die "$provider: unknown iscsi provider. Available [comstar, freenas, istgt, iet, LIO]";
    } elsif ($scfg->{iscsiprovider} eq 'freenas') {
        } elsif ($scfg->{iscsiprovider} eq 'freenas') {
	freenas_user => {
	freenas_password => {
	freenas_use_ssl => {
	freenas_apiv4_host => {
	freenas_user => { optional => 1 },
	freenas_password => { optional => 1 },
	freenas_use_ssl => { optional => 1 },
	freenas_apiv4_host => { optional => 1 },

```

**Comment by TheGrandWazoo** [comment]
@Fernien - Are you using HA for this on Proxmox VE?

**Comment by TheGrandWazoo** [comment]
Oh, did you refresh your browser?

**Comment by Fernien** [comment]
Yes i am using the HA for failover. I have no problems with live migrating that worked without a problem from and to any node as well as creating a machine on it.
Yes i refreshed the browser.
I double checked the ZFSPlugin.pm  again and i actually see this in line 37:
`die "$provider: unknown iscsi provider. Available [comstar, freenas, istgt, iet, LIO]";`

no there are no errors when restarting 
- pvedaemon, pveproxy, pvestatd

> Are you sure there is no errors on the restart of the 'pvemanager', 'pveproxy' or 'pvestatd'?
Was the pvemanager a typo because there is no pvemanager on my cluster just pvedaemon

**Comment by TheGrandWazoo** [comment]
@Fernien - Yes that was a typo...pvedaemon.

I guess do it again and give me that output of the syslog. Maybe the HA daemon may need to be restarted because it might pre-complile the perl scripts before it is executing. I will try and see what process the HA daemon uses.

**Comment by Fernien** [comment]
I just moved the nodes therefore they went offline including the freenas. I'll do another failover test now and keep you updated if that works.

BTW I restarted the services on all nodes again, the output is the same: 

```
root@trick:~# systemctl status pvedaemon
● pvedaemon.service - PVE API Daemon
   Loaded: loaded (/lib/systemd/system/pvedaemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-03-03 16:08:35 CET; 16s ago
  Process: 16099 ExecStart=/usr/bin/pvedaemon start (code=exited, status=0/SUCCESS)
 Main PID: 16102 (pvedaemon)
    Tasks: 4 (limit: 4915)
   Memory: 122.8M
   CGroup: /system.slice/pvedaemon.service
           ├─16102 pvedaemon
           ├─16103 pvedaemon worker
           ├─16104 pvedaemon worker
           └─16105 pvedaemon worker

Mär 03 16:08:34 trick systemd[1]: Starting PVE API Daemon...
Mär 03 16:08:35 trick pvedaemon[16102]: starting server
Mär 03 16:08:35 trick pvedaemon[16102]: starting 3 worker(s)
Mär 03 16:08:35 trick pvedaemon[16102]: worker 16103 started
Mär 03 16:08:35 trick pvedaemon[16102]: worker 16104 started
Mär 03 16:08:35 trick pvedaemon[16102]: worker 16105 started
Mär 03 16:08:35 trick systemd[1]: Started PVE API Daemon.


root@trick:~# systemctl status pveproxy
● pveproxy.service - PVE API Proxy Server
   Loaded: loaded (/lib/systemd/system/pveproxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-03-03 16:08:38 CET; 20s ago
  Process: 16109 ExecStartPre=/usr/bin/pvecm updatecerts --silent (code=exited, status=0/SUCCESS)
  Process: 16111 ExecStart=/usr/bin/pveproxy start (code=exited, status=0/SUCCESS)
 Main PID: 16112 (pveproxy)
    Tasks: 4 (limit: 4915)
   Memory: 126.4M
   CGroup: /system.slice/pveproxy.service
           ├─16112 pveproxy
           ├─16113 pveproxy worker
           ├─16114 pveproxy worker
           └─16115 pveproxy worker

Mär 03 16:08:37 trick systemd[1]: Starting PVE API Proxy Server...
Mär 03 16:08:38 trick pveproxy[16112]: starting server
Mär 03 16:08:38 trick pveproxy[16112]: starting 3 worker(s)
Mär 03 16:08:38 trick pveproxy[16112]: worker 16113 started
Mär 03 16:08:38 trick pveproxy[16112]: worker 16114 started
Mär 03 16:08:38 trick pveproxy[16112]: worker 16115 started
Mär 03 16:08:38 trick systemd[1]: Started PVE API Proxy Server.


root@trick:~# systemctl status pvestatd
● pvestatd.service - PVE Status Daemon
   Loaded: loaded (/lib/systemd/system/pvestatd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-03-03 16:08:41 CET; 25s ago
  Process: 16136 ExecStart=/usr/bin/pvestatd start (code=exited, status=0/SUCCESS)
 Main PID: 16138 (pvestatd)
    Tasks: 1 (limit: 4915)
   Memory: 77.4M
   CGroup: /system.slice/pvestatd.service
           └─16138 pvestatd

Mär 03 16:08:41 trick systemd[1]: Starting PVE Status Daemon...
Mär 03 16:08:41 trick pvestatd[16138]: starting server
Mär 03 16:08:41 trick systemd[1]: Started PVE Status Daemon.
```

**Comment by Fernien** [comment]
I just did the test and it worked. 
Maybe there is something else that has to be restartet?

**Comment by TheGrandWazoo** [comment]
> 
> 
> I just did the test and it worked.
> Maybe there is something else that has to be restartet?

I think the HA service is the process that needs to be started. Proxmox per-compiles the perl so that is why we restart the 3 processes that I have documented. I will try to figure out the HA service and add that to the README.md and my apt repo.

**Comment by Fernien** [comment]
Thank you very much for your help!
I'll let you know in case i find out anything.

**Comment by TheGrandWazoo** [comment]
@Fernien - I believe the pve-ha-lrm and pve-ha-crm might need to be restarted. They are part of the pve-ha-manager package.
If you are up to testing this out, let me know.
