### ISSUE TITLE
filesystem errors after upgrade to Proxmox 6

### ISSUE THREAD

**Issue by raczkow** [TheGrandWazoo/freenas-proxmox#56]
Hi,
After upgrading my Proxmox cluster to the latest 6th version, 5 of my VMs started to have problems with ext4 filesystem. Lots of errors like:
```
Mar 15 10:58:13 owncloud kernel: [44321.724271] EXT4-fs error (device vdb1): htree_dirblock_to_tree:915: inode #11403486: block 45621355: comm apache2: bad entry in directory: rec_len is smaller than minimal - offset=0, inode=0, rec_len=0, name_len=0, size=4096
Mar 15 10:58:13 owncloud kernel: [44321.730807] EXT4-fs error (device vdb1): htree_dirblock_to_tree:915: inode #11403486: block 45621355: comm apache2: bad entry in directory: rec_len is smaller than minimal - offset=0, inode=0, rec_len=0, name_len=0, size=4096
Mar 15 10:58:13 owncloud kernel: [44322.077487] EXT4-fs error (device vdb1): htree_dirblock_to_tree:915: inode #11403486: block 45621355: comm apache2: bad entry in directory: rec_len is smaller than minimal - offset=0, inode=0, rec_len=0, name_len=0, size=4096
Mar 15 10:58:13 owncloud kernel: [44322.084303] EXT4-fs error (device vdb1): htree_dirblock_to_tree:915: inode #11403486: block 45621355: comm apache2: bad entry in directory: rec_len is smaller than minimal - offset=0, inode=0, rec_len=0, name_len=0, size=4096
```
```
Mar 14 06:25:08 smb kernel: [4648051.711295] EXT4-fs error (device vdb1): ext4_lookup:1446: inode #2: comm updatedb.mlocat: deleted inode referenced: 11
Mar 14 20:59:16 smb kernel: [41357.518555] EXT4-fs error (device vdb1): htree_dirblock_to_tree:915: inode #2: block 9249: comm bacula-fd: bad entry in directory: directory entry overrun - offset=0, inode=48796, rec_len=58136, name_len=248, size=4096
Mar 14 22:21:40 smb kernel: [46301.382849] EXT4-fs error (device vdb1): __ext4_new_inode:809: comm touch: reserved inode found cleared - inode=1
```

Fsck cleans all errors, but after a couple of hours (during backup) these errors return. 

Looks like small disks (10-20 GB) are not affected. Only larger ones (100-400 GB). 

i've decided to create new, clean disk in each VM and move data from damaged disks. But filesystem errors shows on new partitions during rsyncing data.

Is Proxmox 6 incompatible with Freenas? Has anyone of you got similar issues? Any advices for me? 

EDIT:
Proxmox: `pve-manager/6.1-7/13e58d5e (running kernel: 5.3.18-2-pve)`
Freenas: `FreeNAS-11.2-U7 (299a0ab8e2)`

**Comment by TheGrandWazoo** [comment]
I have not run into this problem or condition. I am assuming its your VM using EXT4 on a ZVOL. What OS and version is your VM running, if it is coming from the VM? I can try to replicate it.

**Comment by raczkow** [comment]
All VM's were EXT4 on ZVOL.
System: Debian 6, Debian 7, Debian 8, all systems are 32 bit (I know, they're old - I'm going to migrate all VMs to Debian 10 64-bit soon).

I've got 35 VMs on my 4-node cluster. The problem occurred after upgrade to Proxmox 6. Only 5-6 VMs were affected. Most of them had large disks - 100-400 GB.

Fortunately I've found a working workaround for my problem. I've migrated all disks in all VMs to qcow2 files served by NFS on FreeNAS.

I wonder if my problem could be connected with the hardware I use - Mellanox ConnectX-3 Pro 10 Gbit network adapters.

Summary:
FreeNAS with ZFS over ISCSI - ext4 errors
FreeNAS with NFS (qcow2) - no errors

**Comment by TheGrandWazoo** [comment]
And do the VM's receive this error ONLY after the update or how else is the reproducible? Reboot of Proxmox 6? Reboot of VM? Reboot of entire digital ecosystem? I can make a VM use 120Gb ext4 disk using ZFS over iSCSI so I can see what may be happening. Not sure what I can find but you never know. Or is just just after backups? What is the backup type...Shutdown? Pause? Snapshot?

**Comment by raczkow** [comment]
There was no VMs shutdown during Proxmox upgrade - I was migrating them from one host to another. After some time, first VM switch to read-only-mode with filesystem errors. I rebooted it in a single user mode, fixed the filesystem with fsck and everything started to work. After another couple of hours, the filesystem switched to read-only-mode again. After one day, I had got 4 or 5 VMs with the same behaviour.

Some of these VMs just run and are rarely used by users (no I/O on their disks). But everyday at 8pm there is a scheduled backup. Backup runs inside VM and checks every file, looking for changes. It was very often a cause of filesystem errors. I've got plenty of errors when I tried to rsync data from old disk to new one. Errors were both on old disk and on new disk.

It looks like some kind of iSCSI communication problem between Proxmox node and FreeNAS server.

**Comment by TheGrandWazoo** [comment]
I believe this has nothing to do with the FreeNAS plugin. The plugin basically does CRUD-type ops on the extents and zvols via the API (Proxmox does some stuff with iscsiadm).  The plugin does not do any iSCSI block or zfs services. That is up to the Proxmox iSCSI service, which is open-iscsi I believe, and FreeNAS iSCSI service, which is ctladm (CAM Target Layer). Those two programs create the connections and do the iSCSI block transfers...plus add zfs on top of that and what ever VM filesystem on that.
Maybe open-iscsi came with an issue with one of the Proxmox updates.
