### ISSUE TITLE
Remove snapshot / virtual machines

### ISSUE THREAD

**Issue by razerrazer** [TheGrandWazoo/freenas-proxmox#57]
Hi, 

I running the latest version of FreeNAS u3 v 11. with latest version of Proxmox v6.

When i try to remove a virtual machine or a snapshot i got this error : TASK ERROR: error during cfs-locked 'storage-nas02-ssd' operation: Unable to delete lun /dev/zvol/zpool1/PVEPool/vm-100-state-maret at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 212.

Also is it not possible to remove it manual from data store.

error during cfs-locked 'storage-nas02-ssd' operation: Unable to delete lun /dev/zvol/zpool1/PVEPool/vm-100-state-maret at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 212.

**Comment by TheGrandWazoo** [comment]
Yes, you can removed it directly from FreeNAS. This is the issue we have been having with 'shared' targets. We are waiting for FreeNAS to issue a fix which will give a 'force' parameter on the Extent/Target delete API.
The only work around right now is to make a target per VM. It works but kind of messy in the Proxmox VE GUI.

**Comment by razerrazer** [comment]
Do you know when ?

**Comment by razerrazer** [comment]
Hi, I recently get this back from FreeNAS:

william-gr commented 8 minutes ago
What do you mean? This fix is already available in 11.3-U3.2

I running version  FreeNAS-11.3-U3.1 so this is probably in the latest version of FreeNAS now.

**Comment by razerrazer** [comment]
He also mentioned that it should been working since 11.3-U3.1

https://github.com/freenas/webui/pull/3565

**Comment by TheGrandWazoo** [comment]
#51

**Comment by TheGrandWazoo** [comment]
Closing. Fixed in 2.0.0-0beta testing version and upcoming 2.0.0-1 production version.
