### ISSUE TITLE
hashref error at line 404 in FreeNAS.pm

### ISSUE THREAD

**Issue by TheGrandWazoo** [TheGrandWazoo/freenas-proxmox#58]
I have having error on delete as below

```Jun 22 00:30:26 pve pvedaemon[11067]: error during cfs-locked 'storage-fnzfs' operation: REST::Client exception: headers must be presented as a hashref at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 404.
Jun 22 00:30:26 pve pvedaemon[29594]: <root@pam> end task UPID:pve:00002B3B:00168C82:5EF05E0A:qmconfig:101:root@pam: error during cfs-locked 'storage-fnzfs' operation: REST::Client exception: headers must be presented as a hashref at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 404.
```

I am on
Version:
  FreeNAS-11.3-U3.2
PVE 6.2-6
Using latest of master, any idea?

_Originally posted by @coolboy in https://github.com/TheGrandWazoo/freenas-proxmox/issues/51#issuecomment-647341834_

**Comment by TheGrandWazoo** [comment]
@coolboy - Could you post a snip of your syslog before this error occurred. You can view it in the GUI or via SSH session to copy then paste it to the ticket.

Thx

**Comment by TheGrandWazoo** [comment]
In looking at the Proxmox VE perl libs that come installed with the bare system, the HTTP amd LWP seems like it might do the trick and removing the need for the additional librest-client-perl module or /usr/perl5/REST/Client.pm and its deprecation from this package.
I will currently be developing to these libs in the 'master' repo.

As always, comments are always welcomed.

**Comment by coolboy** [comment]
Hi @TheGrandWazoo 

Thanks for the update I will test your suggested fix for now and looking fwd to your update of getting rid of the old rest perl module

**Comment by coolboy** [comment]
BTW, I am using this way to patch the pve, which I guess is the manual way?
https://xinux.net/index.php/Proxmox_iscsi_over_zfs_with_freenas

I also tried the auto way which mentioned in this repo as below
```
wget http://repo.ksatechnologies.com/debian/pve/ksatechnologies-release.gpg -O /etc/apt/trusted.gpg.d/ksatechnologies-repo.gpg
echo "deb http://repo.ksatechnologies.com/debian/pve stable freenas-proxmox" > /etc/apt/sources.list.d/ksatechnologies-repo.list
```

Which doesn't work for me, at least I can't see freenas dropdown shows up

I am happy to help of debugging this issue as well

**Comment by coolboy** [comment]
I tested manual update below and can confirm the problem fixed

```cp perl5/REST/Client.pm /usr/share/perl5/REST/Client.pm
systemctl restart pvedaemon
systemctl restart pveproxy```

**Comment by TheGrandWazoo** [comment]
@coolboy - I am glad it is working for you.
Make sure after you add the repo you do a
```
apt update
apt [dist|full]-upgrade
```
This will do the automatic installs and updates.
And there is two repos a stable and a testing. The testing has the most current which is 2.0.0-0beta which I will most likely updating the stable to be 2.0.0-1.
Thanks again for your support.
