### ISSUE TITLE
Unable to connect to FreeNAS API, error during cfs-locked operation, API replies with 307 temporary redirect

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [TheGrandWazoo/freenas-proxmox#59]
Hello,  

This evening I tried to get the add-on to work, but it seems to fail at the FreeNAS API somewhere.   
I've searched a bit, and thought both issue #34 and #44 would fix my problems - but they don't.   
I don't know how to fix this exactly, what am I missing? 

Error during creation of a VM:  
```
TASK ERROR: unable to create VM 109 - error during cfs-locked 'storage-nasferatu-iscsi' operation: Unable to connect to the FreeNAS API service at '10.69.70.10' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241.
``` 

Error during the removal of the disk that got created (but the VM itself is unknown for Proxmox):  
```
Unable to connect to the FreeNAS API service at '10.69.70.10' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241. (500)
```

The log in /var/log/syslog mentions following lines: 
```
Jun 25 23:06:59 hypervisor1 pvedaemon[4340]: <root@pam> starting task   UPID:hypervisor1:00002AF0:000089B1:5EF511F3:qmcreate:109:root@pam:   
Jun 25 23:07:00 hypervisor1 systemd[1]: Starting Proxmox VE replication runner...   
Jun 25 23:07:00 hypervisor1 pvedaemon[10992]: FreeNAS::lun_command : create_lu(/dev/zvol/v1/iscsi/vm-109-disk-0)
Jun 25 23:07:00 hypervisor1 pvedaemon[10992]: [ERROR]FreeNAS::API::freenas_api_call : Response code: 307
Jun 25 23:07:00 hypervisor1 pvedaemon[10992]: [ERROR]FreeNAS::API::freenas_api_call : Response content: <html>#015#012<head><title>307 Temporary Redirect</title></head>#015#012<body>#015#012<center><h1>307 Temporary Redirect</h1></center>#015#012<hr><center>nginx</center>#015#012</body>#015#012</html>#015
Jun 25 23:07:00 hypervisor1 pvedaemon[10992]: VM 109 creating disks failed
Jun 25 23:07:00 hypervisor1 pvedaemon[10992]: unable to create VM 109 - error during cfs-locked 'storage-nasferatu-iscsi' operation: Unable to connect to the FreeNAS API service at '10.69.70.10' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241.
Jun 25 23:07:00 hypervisor1 pvedaemon[4340]: <root@pam> end task UPID:hypervisor1:00002AF0:000089B1:5EF511F3:qmcreate:109:root@pam: unable to create VM 109 - error during cfs-locked 'storage-nasferatu-iscsi' operation: Unable to connect to the FreeNAS API service at '10.69.70.10' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241.
```

I have upgraded both machines, before FreeNAS was on 11.2.x, now on FreeNAS 11.3-RELEASE-p9. Proxmox went from pve-manager/6.2-6/ee1d7754 (running kernel: 5.4.44-1-pve) to pve-manager/6.2-6/ee1d7754 (running kernel: 5.4.44-1-pve), I haven't noted what got upgraded but it was some minor stuff, not directly related to VMs and storage.     

The config on both machines:  

![afbeelding](https://user-images.githubusercontent.com/42654642/85796381-23831200-b73a-11ea-95d7-ba407f6519e6.png)

![afbeelding](https://user-images.githubusercontent.com/42654642/85796826-dfdcd800-b73a-11ea-8413-1ef69a7b86d6.png)
Changing the HTTP > HTTPS redirect to disabled did not change a thing, and I tried to set the web UI on a fixed IP as well. But both did not change it.   

Command `ssh -i /etc/pve/priv/zfs/10.69.70.10_id_rsa root@10.69.70.10` works fine.  

I have tried switching the datasets to the root dataset, a sub dataset, and a dataset with the default suggested permissions from FreeNAS. Root has full RWX with that one.    

Both machines had a full reboot, firewall doesn't seem to be an issue since proxmox gets a 307 and the disks are being created.

**Comment by TheGrandWazoo** [comment]
First, was this working before?

I don't have the redirect checked on mine. Try turning that off.

Lastly, if you can post the syslog from Proxmox for the attempted commits that would be helpful.

**Comment by TheGrandWazoo** [comment]
Looking at this a bit more, I believe the redirection is causing the issue. The underlying REST client does not support redirect so i believe it fails.

**Comment by TheGrandWazoo** [comment]
I reformatted the syslog and  can see the 307 redirect better.  It is not support in the librest-client-perl lib.

Looks like I am going to have to up my development to the new libs...I hope they can handle the redirect.

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
> 
> 
> First, was this working before?
> 
> I don't have the redirect checked on mine. Try turning that off.
> 
> Lastly, if you can post the syslog from Proxmox for the attempted commits that would be helpful. - Oops, never mind, I see it.

This was the first time I tried to install it, it has not worked at all.    



I had the redirect enabled, because it was enabled in #44, so I thought it would be good to use a working example.   
Now after I've disabled the redirect, I do get another error message, it seems that I have missed something in my configuration.   

`Jun 26 01:28:15 hypervisor1 pvedaemon[1337]: <root@pam> starting task UPID:hypervisor1:00004E7D:000D78D1:5EF5330F:qmcreate:110:root@pam:
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::lun_command : create_lu(/dev/zvol/v1/iscsi/vm-110-disk-1)
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_target() : sucessfull
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_target_to_extent() : sucessfull
Jun 26 01:28:16 hypervisor1 pvedaemon[20093]: FreeNAS::API::freenas_get_first_available_lunid : return 0
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_target() : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_target() : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::API::freenas_list_lu : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::list_lu(/dev/zvol/v1/iscsi/vm-110-disk-1):name : lun not found
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_globalconfig : target_basename=iqn.2005-10.org.freenas.ctl
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::api_call : setup : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: FreeNAS::API::get_target() : sucessfull
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: VM 110 creating disks failed
Jun 26 01:28:17 hypervisor1 pvedaemon[20093]: unable to create VM 110 - error during cfs-locked 'storage-nasferatu-iscsi' operation: Unable to find the target id for iqn.2005-10.org.freenas.ctl at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.
Jun 26 01:28:17 hypervisor1 pvedaemon[1337]: <root@pam> end task UPID:hypervisor1:00004E7D:000D78D1:5EF5330F:qmcreate:110:root@pam: unable to create VM 110 - error during cfs-locked 'storage-nasferatu-iscsi' operation: Unable to find the target id for iqn.2005-10.org.freenas.ctl at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 149.`      

So the HTTP > HTTPS redirect does cause an issue, but it should work without the redirection enabled.   

I'll take a look at it now.

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
Okay so the creation of VMs is working now.   
Due to the redirect issue, I didn't get to other issues, but I had to append the ISCSI target name to the proxmox target - instead of `iqn.2005-10.org.freenas.ctl` it should have been `iqn.2005-10.org.freenas.ctl:iscsi-san`. I though I'd mention it, since I saw it in another issue and had to google for a bit on how it should be formatted.   

I can't delete the old VM disks that got created but otherwise didn't work, but that's probably due to commands only being partially executed I guess. They can be wiped in the FreeNAS web UI without problems.    


So the only real problem here is the redirect failing with new libraries, which probably would be a mention worth in README?

**Comment by TheGrandWazoo** [comment]
Testing repo has been updated with freenas-proxmox-2.0.0-0~beta2_all.deb

**Comment by barthohomeautomation** [comment]
I have run into what I believe is the same or similar issue and cannot seem to get past this. I have tried every solution I can find including running the patches from the testing repository. I am attempting to move the disk from the current storage location to the newly created ZFS on iSCSI storage.

Error I am receiving:
`create full clone of drive scsi0 (Jarhead-Virtual:201/vm-201-disk-0.raw)
TASK ERROR: storage migration failed: error during cfs-locked 'storage-Jarhead-VM-Lab' operation: Unable to connect to the FreeNAS API service at '10.0.1.4' using the 'https' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375.`

Information from syslog:
`Jan  9 14:02:52 proxmox pvedaemon[1299]: <michael@pam> move disk VM 201: move --disk scsi0 --storage Jarhead-VM-Lab
Jan  9 14:02:52 proxmox pvedaemon[1299]: <michael@pam> starting task UPID:proxmox:00000C25:000097FD:5FFA0BEC:qmmove:201:michael@pam:
Jan  9 14:02:54 proxmox pvedaemon[3109]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : create_lu(/dev/zvol/Jarhead/Proxmox-Lab/Proxmox-VirtualMachines/vm-201-disk-0)
Jan  9 14:02:54 proxmox pvedaemon[3109]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
Jan  9 14:02:54 proxmox pvedaemon[3109]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Jan  9 14:02:54 proxmox pvedaemon[3109]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Redirecting to HTTPS protocol
Jan  9 14:02:54 proxmox pvedaemon[3109]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Jan  9 14:02:54 proxmox pvedaemon[3109]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response code: 401
Jan  9 14:02:54 proxmox pvedaemon[3109]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response content:
Jan  9 14:02:54 proxmox pvedaemon[3109]: storage migration failed: error during cfs-locked 'storage-Jarhead-VM-Lab' operation: Unable to connect to the FreeNAS API service at '10.0.1.4' using the 'https' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375.
Jan  9 14:02:54 proxmox pvedaemon[1299]: <michael@pam> end task UPID:proxmox:00000C25:000097FD:5FFA0BEC:qmmove:201:michael@pam: storage migration failed: error during cfs-locked 'storage-Jarhead-VM-Lab' operation: Unable to connect to the FreeNAS API service at '10.0.1.4' using the 'https' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375.
Jan  9 14:03:00 proxmox systemd[1]: Starting Proxmox VE replication runner...`

I have tried to both 0.0.0.0 and IP in WebGUI and redirect both on and off.

Any thoughts on how to resolve this issue?

**Comment by barthohomeautomation** [comment]
Since this appears to be a slightly different issue, I will open a new issue.
