### ISSUE TITLE
Proxmox 6.2-4 + TrueNAS CORE 12.0 BETA - "Unable to connect to API"

### ISSUE THREAD

**Issue by basementcloud** [TheGrandWazoo/freenas-proxmox#60]
I just tested the (stable) plugin with the latest TrueNAS 12.0 BETA and am getting this error when trying to add a disk to a VM...

`error during cfs-locked 'storage-tank-iscsi' operation: Unable to connect to the FreeNAS API service at '192.168.1.142' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241. at /usr/share/perl5/PVE/API2/Qemu.pm line 1334. (500)`

I think TrueNAS/FreeNAS is now using API Keys instead of a username/password for API login. Tried both http and https.

I'm happy to do further testing with this setup if needed.

Cheers!

**Comment by basementcloud** [comment]
It appears I could be wrong about my initial thoughts, not sure why it's giving a 302 code, redirection from HTTP -> HTTPS is turned off.
That said, since they are now implementing API Keys, perhaps the Plugin GUI could use an update. Maybe a version dropdown to offer different fields?

Here's the relevant log section...

`Jul  4 16:44:21 pve-test pvedaemon[2459]: <root@pam> update VM 100: -scsi1 tank-iscsi:2,discard=on
Jul  4 16:44:21 pve-test pvedaemon[2459]: <root@pam> starting task UPID:pve-test:00000EF5:0000A033:5F00EA25:qmconfig:100:root@pam:
Jul  4 16:44:22 pve-test pvedaemon[3829]: FreeNAS::lun_command : create_lu(/dev/zvol/tank/iscsi/vm-100-disk-0)
Jul  4 16:44:22 pve-test pvedaemon[3829]: [ERROR]FreeNAS::API::freenas_api_call : Response code: 302
Jul  4 16:44:22 pve-test pvedaemon[3829]: [ERROR]FreeNAS::API::freenas_api_call : Response content: <html>#015#012<head><title>302 Found</title></head>#015#012<body>#015#012<center><h1>302 Found</h1></center>#015#012<hr><center>nginx</center>#015#012</body>#015#012</html>#015
Jul  4 16:44:22 pve-test pvedaemon[3829]: VM 100 creating disks failed
Jul  4 16:44:22 pve-test pvedaemon[3829]: error during cfs-locked 'storage-tank-iscsi' operation: Unable to connect to the FreeNAS API service at '172.30.100.142' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241.
Jul  4 16:44:22 pve-test pvedaemon[2459]: <root@pam> end task UPID:pve-test:00000EF5:0000A033:5F00EA25:qmconfig:100:root@pam: error during cfs-locked 'storage-tank-iscsi' operation: Unable to connect to the FreeNAS API service at '172.30.100.142' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 241.
`

**Comment by TheGrandWazoo** [comment]
I think this is the first TrueNAS that I have seen using the plugin. I am not sure if I can download the TrueNAS software or not but I will at least try to figure this out. The 302 seems to have just shown up so I need to further investigate the and ramp up the development to change over to perl libs that can handle the 302.
I might need a tcpdump or trace to see the internals of the 302, if that is possible.
I will also look into the API key. I like that idea.

**Comment by basementcloud** [comment]
Thanks Kevin.

They are no longer developing FreeNAS as of version 12. It's TrueNAS CORE going forware, and TrueNAS Enterprise with a license key.

You can read more and download the 12.0-BETA from their site (see link in their big post).
https://www.ixsystems.com/blog/truenas-12-beta/

I have it installed in VM for testing.

**Comment by TheGrandWazoo** [comment]
@basementcloud : Will be loading up a TrueNAS 12 CORE instance to see what is new and can be changed. I currently look for the FreeNAS/TrueNAS product word and version in the 'freenas_api_check' function.
I'll also check to see if Proxmox does any AJAX stuff in their Javascript code so I maybe able to autofill (don't hold your breath)

**Comment by TheGrandWazoo** [comment]
Ok, so the issue is my regexp statement that checks and parses the version of FreeNAS/TrueNAS does not know what to do with 12.0-BETA so the actual value become 0 which is < 11030100. Have a new version of the regexp that you can try by editing the /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm file at line 368. Replace the following:
```
^(\w+)\-(\d+)\.(\d+)\-U(\d+)\.?(\d?)
```
with
```
^(\w+)\-(\d+)\.(\d+)\-(?:U|BETA)(\d?)\.?(\d?)
```
This should give the results of 12000000 which is now > 11030100 and will use the v2.0 API's.

I believe the v1.0 API's redirect to the v2.0 API's and thus giving the redirection message.

I am currently testing it myself.

**Comment by TheGrandWazoo** [comment]
I have to change one more v1.0 hardcoded call that is actually the version getter. Standby!!!

**Comment by basementcloud** [comment]
Awesome! Thanks Kevin.

Keep me posted, I'll test it this evening.

**Comment by TheGrandWazoo** [comment]
And down the FreeNAS/TrueNAS rabbit hole I went, then shaved a yak in Tibet...again.

Well API v1.0 gave you the version in...JSON....API. It was great. Simple. Well, v2.0 gives you the version in a...STRING...WITH DOUBLE QUOTES ON BOTH ENDS. OMG, stick with a format iXsystems.

So, a bit more magic had to happen to figure out the version.

**Comment by basementcloud** [comment]
Nice! Nothing like a good challenge on Motivation Monday ;)

Any idea on how you might address using the API key for TrueNAS Core? I wonder if they left the username/password combo for backwards compatibility?
Will test this evening once I know which files to update? Or will you be updating the testing repo?

...I should make that a separate feature/bug for taking ;)

Awesome addition to Proxmox btw, thanks for all the effort and maintenance!

**Comment by TheGrandWazoo** [comment]
I will be updating the test repo with the changes. I had to move on to another project...honey do's. Should have it uploaded in the AM.

I did not see the API key in the GUI but I was just glancing through. I did see one with using an auth API call with a username and password to get a key but then that made no sense cause it will expire and then you would still need the username and password to rekey. If you could point me to some mention of it I would appreciate it.

I am glad people are making use of the plugin.

**Comment by TheGrandWazoo** [comment]
Testing repo has been updated with freenas-proxmox-2.0.0-0~beta2_all.deb
