### ISSUE TITLE
"error with cfs lock" on second hard disk creation

### ISSUE THREAD

**Issue by askeveryman** [TheGrandWazoo/freenas-proxmox#62]
**Problem**
Attempts to create a VM's second (third, fourth, fifth...) hard drive intermittently fail with

> error with cfs lock 'storage-zSCSI': Unable to create lun /dev/zvol/tank/vm-100-disk-4 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 271. at /usr/share/perl5/PVE/API2/Qemu.pm line 1274. (500)

The virtual disk extent IS created on the FreeNAS/TrueNAS side but is not attached to the VM.  

Not every attempt fails -- I note that waiting a minute or two usually leads to success.

**Steps to reproduce**

1. Create a new VM
2. Immediately add a second hard drive

**Comment by TheGrandWazoo** [comment]
Thanks for reporting. I believe I have found the issue and just trying to work a proper solution.
For some reason this procedure takes a different path so the pointer variable to the hashref does not get initialized.
Should have a fix today.

**Comment by askeveryman** [comment]
Thanks, and thanks for all your work on this.  It's an elegant, scalable solution that removes practical barriers to using iSCSI.  It also eliminates the

> ctld: read: connection lost

messages that spam the FreeNAS console when using, say, LVM over iSCSI.
