### ISSUE TITLE
http://repo.ksatechnologies.com appears to be down

### ISSUE THREAD

**Issue by bbergquist0930** [TheGrandWazoo/freenas-proxmox#63]
Don't know a better way of reporting the issue but http://repo.ksatechnologies.com appears to be down so the package cannot be downloaded.

**Comment by TheGrandWazoo** [comment]
Thank you for reporting it. I had an alert this morning from my BCM that I had an uncorrectable ECC error on my FreeNAS and needed a push.
Should be up and running in a few minutes.

**Comment by TheGrandWazoo** [comment]
Backup and running. Tested with new version of freenas-proxmox-2.0.0-0~beta4.
