### ISSUE TITLE
Problems inside VM

### ISSUE THREAD

**Issue by razerrazer** [TheGrandWazoo/freenas-proxmox#68]
Hi,

After a while when the vm is turned on  i get this issue to run any command at the server:
bash: /usr/bin/ping6: cannot execute binary file: Exec format error

And if i  restart the virtual machine, it comes back online again without issues for a couple of hours, the the issue is back.

And if i check dmesg on one of the host i get this error message:
Warning! Received an indication that the LUN reached a thin provisioning soft threshold.

**Comment by raczkow** [comment]
Check if you have ext4 errors inside your VM.

**Comment by razerrazer** [comment]
The system is now read only, i'm not able to restart it

But if i restart a few times it works as it should same for all vms not just one!

So this is somehow storage related. And i have about 8 TB free space of my SSD pool.

**Comment by raczkow** [comment]
Boot the VM from SystemRescueCD and check its filesystem with fsck.

**Comment by raczkow** [comment]
Check if https://github.com/TheGrandWazoo/freenas-proxmox/issues/56 is similar to your problem.

**Comment by razerrazer** [comment]
It sounds similar, i'm sure this is working without issues if i switch over to original iscsi instead of using zfs over iscsi.

I also have a vmware platform live and that one is working without issue.

**Comment by razerrazer** [comment]
This is a new created vm, it should not giving you file system errors.

It giving you it because it losing the connection to the LUN of FreeNAS.

**Comment by raczkow** [comment]
I don't know if typical iscsi works OK. I bet it's some hardware issue between Proxmox and FreeNAS. I switched to NFS and all my VMs are qcow images now.

What hardware do you useas NIC? My cluster uses Mellanox ConnectX-3 Pro 10 Gbit network adapters and I think they break everything.

**Comment by raczkow** [comment]
And my problem has started just after upgrade to Proxmox 6. Proxmox 5 and ZFS-over-iSCSI worked without any problems for almost a year.

**Comment by razerrazer** [comment]
I have four hosts with 2x intel x520 nics per hosts.
I recently upgraded the Freenas-Proxmox plugin to the latest testing repository and then the problem started.

Before summer i used it with stable branch, and it working without issues except that you was not able to remove a virtual machine, so i had to upgrade to get that working.

And this is a new proxmox 6 hosts from beginning, i have never upgraded it from 5 or so.

And when i was using iscsi with multipath i was not experiencing this type of problems.

**Comment by razerrazer** [comment]
So far with iscsi and multipath, no issues at all.

So the problem is related to the plugin unfortunately :(

**Comment by TheGrandWazoo** [comment]
The plugin does NOT do any block writing of the data between Proxmox and FreeNAS. That is up to the ZFS and iSCSI drivers/executables used in the Debian/Ubuntu distro of Proxmox and FreeBSD of FreeNAS/TrueNAS.
