### ISSUE TITLE
Cannot uninstall  freenas-proxmox package with repo

### ISSUE THREAD

**Issue by Spreadneck** [TheGrandWazoo/freenas-proxmox#71]
I tried to use the repo but never saw the FreeNAS-API option in the web GUI so I decided to uninstall and reinstall manually. However I encounter this error when i use the uninstall command. 

`apt remove freenas-proxmox' 

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  freenas-proxmox
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 58387 files and directories currently installed.)
Removing freenas-proxmox (2.0.0-1) ...
Reinstalling original Proxmox VE files
Restarting pvedaemon...
Attempt to reload PVE/Storage.pm aborted.
Compilation failed in require at /usr/share/perl5/PVE/AbstractConfig.pm line 9, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/AbstractConfig.pm line 9, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/QemuConfig.pm line 6, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/QemuConfig.pm line 6, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/HA/Resources/PVEVM.pm line 10, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/HA/Resources/PVEVM.pm line 19, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/HA/Env/PVE2.pm line 21, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/HA/Env/PVE2.pm line 21, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/API2/Cluster.pm line 14, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2/Cluster.pm line 14, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/API2.pm line 14, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2.pm line 14, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/Service/pvedaemon.pm line 8, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/Service/pvedaemon.pm line 8, <DATA> line 755.
Compilation failed in require at /usr/bin/pvedaemon line 11, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/bin/pvedaemon line 11, <DATA> line 755.
dpkg: error processing package freenas-proxmox (--remove):
 installed freenas-proxmox package post-removal script subprocess returned error exit status 255
Errors were encountered while processing:
 freenas-proxmox
E: Sub-process /usr/bin/dpkg returned an error code (1)

What can I do to remove the package and start over?

**Comment by TheGrandWazoo** [comment]
Should be able to do a 'apt remove freenas-proxmox' and that should solve the issue.

You can also try 'apt reinstall freenas-proxmox'.

I believe the reason for the error was the original 1.0.0 version did not have a 'postrm' to remove it.

**Comment by TheGrandWazoo** [comment]
@Spreadneck - Just checking to see if the above worked for you?

**Comment by Spreadneck** [comment]
@TheGrandWazoo Sorry, just getting to reviewing this today. I actually have a bigger issue now as pvedaemon won't start today. I tried to reinstall and got this output:

`root@pve01:~# apt remove freenas-proxmox
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  freenas-proxmox
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 58387 files and directories currently installed.)
Removing freenas-proxmox (2.0.0-1) ...
Reinstalling original Proxmox VE files
Restarting pvedaemon...
Attempt to reload PVE/Storage.pm aborted.
Compilation failed in require at /usr/share/perl5/PVE/AbstractConfig.pm line 9, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/AbstractConfig.pm line 9, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/QemuConfig.pm line 6, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/QemuConfig.pm line 6, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/HA/Resources/PVEVM.pm line 10, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/HA/Resources/PVEVM.pm line 19, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/HA/Env/PVE2.pm line 21, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/HA/Env/PVE2.pm line 21, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/API2/Cluster.pm line 14, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2/Cluster.pm line 14, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/API2.pm line 14, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/API2.pm line 14, <DATA> line 755.
Compilation failed in require at /usr/share/perl5/PVE/Service/pvedaemon.pm line 8, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/share/perl5/PVE/Service/pvedaemon.pm line 8, <DATA> line 755.
Compilation failed in require at /usr/bin/pvedaemon line 11, <DATA> line 755.
BEGIN failed--compilation aborted at /usr/bin/pvedaemon line 11, <DATA> line 755.
dpkg: error processing package freenas-proxmox (--remove):
 installed freenas-proxmox package post-removal script subprocess returned error exit status 255
Errors were encountered while processing:
 freenas-proxmox
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@pve01:~#
`
