### ISSUE TITLE
Support for TrueNAS SCALE

### ISSUE THREAD

**Issue by hans00** [TheGrandWazoo/freenas-proxmox#75]
Known bug:
- Version string parse error
```
PVE::Storage::LunCmd::FreeNAS::freenas_api_check : successful : Server version: TrueNAS-SCALE-20.08-MASTER-20200824-142916
Argument "test-iscsi" isn't numeric in sprintf at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 403.
```
- SCST doesn't allow character '/'
```
FATAL: Device 'storage/vm-222-disk-0' configured for handler 'vdisk_blockio' may not contain character '/'.
```

**Comment by TheGrandWazoo** [comment]
hans - Thank you for your pull request. I will need to test these changes against FreeNAS and TrueNAS-Core before I place them into the mainstream code.

**Comment by TheGrandWazoo** [comment]
@hans00 - Thank you for your pull request. I will need to test these changes against FreeNAS and TrueNAS-Core before I place them into the mainstream code.

**Comment by TheGrandWazoo** [comment]
@hans00 - I am assuming the SCST is the new iSCSI initiator used in TrueNAS Scale?

**Comment by hans00** [comment]
Yes the TrueNAS Scale use SCST.

**Comment by aanon4** [comment]
I notice this tweak for SCALE is different in the current code. I'm bumping into an issue where I try to use a pool called "tank/vm" rather than just "tank". It works fine but I have to go in and fix the extent name because it ends up with a / in it. This original fix handled that case while the current fix doesn't. Everything works fine once the name has been fixed.

**Comment by TheGrandWazoo** [comment]
@aanon4 - Could you provide some output of the issue. Syslog should pickup the error so I can see what needs to be fixed.

**Comment by hans00** [comment]
It may bug on this line
https://github.com/TheGrandWazoo/freenas-proxmox/blob/master/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L513

Will trigger SCST naming policy if the pool name contains slash.
It should patch the pool name also.

**Comment by TheGrandWazoo** [comment]
> 
> 
> It may bug on this line
> https://github.com/TheGrandWazoo/freenas-proxmox/blob/master/perl5/PVE/Storage/LunCmd/FreeNAS.pm#L513
> 
> Will trigger SCST configure error if the pool name contains slash.
> It should patch the pool name also.

    $name  = $scfg->{'pool'} . ($product_name eq "TrueNAS-SCALE" ? '-' : '/') . $name;

So you're saying that $scfg->{'pool'} needs to have any '/' (slashes) turned into a '-' (dash)?
Do $name need it also?

**Comment by hans00** [comment]
In PVE case, `$name` not need convert.
But `$scfg->{'pool'}` should convert any slash into SCST allows characters.

The actual configuration check:
https://github.com/openunix/scst/blob/a85ae9e6a110299e62b1f0ca4df58a2d470dc184/scstadmin/scstadmin.sysfs/scstadmin#L2071

Allow starts of `/dev/` , but not allow slash.

**Comment by TheGrandWazoo** [comment]
@hans00 - Thanks for your help on this. I'll get a fix going plus I will spin up a SCALE VM for testing.

**Comment by aanon4** [comment]
@hans00 thanks for jumping on this for me! Just circling back to this today and you've done all my work for me - much appreciated. Fantastic software @TheGrandWazoo, let me know if I need to add and/or test anything for you.

**Comment by TheGrandWazoo** [comment]
Fix has been committed for Beta testing.

**Comment by aanon4** [comment]
Fantastic - works a treat! Thank you.

**Comment by TheGrandWazoo** [comment]
Thank you for working with me to get a fix in place.

**Comment by TheGrandWazoo** [comment]
Closing due to fix in place.
