### ISSUE TITLE
Issues mounting ZFS on TrueNAS Core 12RC1

### ISSUE THREAD

**Issue by bitblt** [TheGrandWazoo/freenas-proxmox#78]
I upgraded my FreeNAS 11.x to TrueNAS Core 12 RC1 and Proxmox 6 was no longer able to mount disks using ZFS over iSCSI.  I kept getting the following error message: "Could not find lu_name for zvol vm-101-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 118"

I did some troubleshooting and was able to resolve this issue by patching FreeNAS.pm.  The issue was the version name TrueNAS-12.0-RC1 wasn't be handled by the regex.

The workaround involves a single line change on line 402 of /usr/share/perl5/PVE/Storage/FreeNAS.pm:
original: $result->{'fullversion'} =~ s/^(\w+)\-(\d+)\.(\d+)\-(?:U|BETA)(\d?)\.?(\d?)//;
patched: $result->{'fullversion'} =~ s/^(\w+)\-(\d+)\.(\d+)\-(?:U|BETA|RC)(\d?)\.?(\d?)//;

I restarted the appropriate daemons and it restored access.

**Comment by TheGrandWazoo** [comment]
@bitblt - Hi. This was fixed in commit 084faf9903c97cc86aab6548868305eee7c3fe2c. I am not sure I did a pull request to the V2.0 branch but I will check and let you know.

**Comment by TheGrandWazoo** [comment]
Pull request #80 and build complete for stable branch.

**Comment by TheGrandWazoo** [comment]
Should be fix after a apt-get update and apt-get [full|dist]-upgrade.
