### ISSUE TITLE
Task Failed when trying to delete a ZFS over iSCSI volume via the proxmox web interface.

### ISSUE THREAD

**Issue by lyonscf** [TheGrandWazoo/freenas-proxmox#79]
I'm using the stable debian repo on the current latest version, everything is up to date:

deb http://repo.ksatechnologies.com/debian/pve stable freenas-proxmox

Truenas
--
Platform: Generic
Version: TrueNAS-12.0-BETA2.1

Proxmox
--

Platform: x86_64
Version: Virtual Environment 6.2-12

<img width="755" alt="Screenshot 2020-10-12 at 14 11 16" src="https://user-images.githubusercontent.com/206170/95750418-05173700-0c95-11eb-88d7-c4032fa631b1.png">

**Comment by TheGrandWazoo** [comment]
@lyonscf - I believe this was fixed in commit 084faf9903c97cc86aab6548868305eee7c3fe2c but I don't think I did a pull request to the V2.0 branch. I am checking and will let you know.

**Comment by lyonscf** [comment]
Ok, thanks a bunch! Great work on this btw!

**Comment by TheGrandWazoo** [comment]
@lyonscf - Thanks for you support and using the product.

I will be merging the master to V2 branch in a bit.

**Comment by TheGrandWazoo** [comment]
Merger request #80 and build complete.

**Comment by lyonscf** [comment]
Updated and tested on my side with a fresh vm (deployed, started, shutdown and deleted with purge), it seems to be working!

Thank you for the support and a great product!

**Comment by TheGrandWazoo** [comment]
@lyonscf - Thanks Colin.
