### ISSUE TITLE
Error during VM creation or any other task

### ISSUE THREAD

**Issue by jacobq11** [TheGrandWazoo/freenas-proxmox#82]
Everytime I try to make a vm I get the following error:
`error during cfs-locked 'storage-FreeNAS-iSCSI' operation: command '/usr/bin/ssh -o 'BatchMode=yes' -i /etc/pve/priv/zfs/172.17.0.1_id_rsa root@172.17.0.1 zfs list -o name,volsize,origin,type,refquota -t volume,filesystem -Hrp' failed: got timeout`

I don't think that the SSH keys are messed up since It is able to see the total size and usage of the pool.

Any assistance would be greatly appreciated.

**Comment by TheGrandWazoo** [comment]
@jacobq11 - Have you tried to ping the FreeNAS machine? If so, then make sure SSH is enabled on the FreeNAS. Also, make sure the Web UI is bond to ALL interfaces. At the moment, you can't have the WEB UI and the API service bonded to different interfaces.

**Comment by jacobq11** [comment]
Thanks for point me in the right direction. I found the problem. 

I wanted to get everything on my SAN running jumbo frames so I set the MTU to 9000 and both freenas and proxmox. Well when I set the MTU to 9000 on our Juniper QFX5100 that's when stuff went sideways. Long story short I have to set the Juniper MTU to 9216 and everything is working as expected.
