### ISSUE TITLE
TASK ERROR: freenas: unknown iscsi provider. Available [comstar, istgt, iet, LIO] at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 35.

### ISSUE THREAD

**Issue by kurdam** [TheGrandWazoo/freenas-proxmox#83]
Hi, 
I'm having a bit of a catastrophic failure on this monday morning.
i've been using your connector to link my proxmox datacenter to my freenas for about 2 months now.
I use this connector to store a VM disk for one of my VMs (PBS but it doesn't matter).
The VM may have crashed during the weekend because HA tried to migrate it to my other nodes.
Coming this morning, I tried to start it but i'm getting this message:
TASK ERROR: freenas: unknown iscsi provider. Available [comstar, istgt, iet, LIO] at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 35. 
It looks like the Freenas API is not detected. But i'm still able to see the storage, and on the GUI side everything looks OK.
I can see the freenas storage and what's in it but if i try to add another ZFS over ISCSI it doesn't show me the freenas option anymore.
Do you have any idea on what could have happend and how i can fix that ?
Thanks in advance.
![image](https://user-images.githubusercontent.com/32850648/98521217-74bc1a00-2273-11eb-978b-52bc49ff6770.png)
![image](https://user-images.githubusercontent.com/32850648/98521434-b8af1f00-2273-11eb-861b-109d03951951.png)
![image](https://user-images.githubusercontent.com/32850648/98521497-ccf31c00-2273-11eb-831c-725317a96d09.png)
![image](https://user-images.githubusercontent.com/32850648/98521616-f57b1600-2273-11eb-9a8d-141e1daf9722.png)
![image](https://user-images.githubusercontent.com/32850648/98521686-0cba0380-2274-11eb-86ea-1c2e595fc433.png)

**Comment by TheGrandWazoo** [comment]
@kurdam - From the looks of it the patches are no longer applied to the ZFSPlugin.pm, pvemanagerlib.js and apidoc.js. Did you by chance do an 'apt update' and not apply the patches? Are you using the package that automatically does the upgrades?

**Comment by kurdam** [comment]
Hi, thank you for your quick answer.
My boss did a pve update during the weekend. 
So what i did today is redo complitely the tutorials (yours and this one https://forum.proxmox.com/threads/guide-setup-zfs-over-iscsi-with-pve-5x-and-freenas-11.54611/) without success.
The problem is that my cluster doesn't see the field with freenas api when i try to add a new ZFS over ISCSI device.
Even when i try to apply the patches everything is going fine (i get no particular error) but in the end, the result is the same.
The strange behaviour in all of this is that i can still see the storage as shown in my previsous screenshot.

I'm a bit lost on what i can do. If you need the output of some commands or some of my configs file, i would be happy to send them to you.

**Comment by TheGrandWazoo** [comment]
@kurdam - Seeing the contents relies on the SSH portion, not the plugin itself. The plugin setups the luns and extents via the API's.
So, just to make sure you did the procedures in the tutorials on each of the nodes in the cluster? You restarted the 3 daemons one each of the nodes in the cluster?
I do strongly encourage to use the repo that will automatically patch, update and restart daemons with a 'apt [dist|full]-update is issued.
If you need some help, I can do a remote session with you (Skype, Zoom or whatever you like) and see or help resolve your problem, if you'd like.

**Comment by kurdam** [comment]
Thank you. I have managed to do it somehow.
I redid the procedure and magically it worked. Unfornuately PBS couldn't see me datastore so i destroyed it and moved my backups on another storage.
I will use the freenas connection for less sensitive datas.

My guess is yesterday i was working on anoter backup server with veeam and i had to force an older cipher for ssh connections. That maybe what was blocvking the conection because i removed it this morning because it was blocking me for migrations.

Thank you a lot again.

**Comment by chanster** [comment]
So I got a similar error

```
task started by HA resource agent
TASK ERROR: freenas: unknown iscsi provider. Available [comstar, istgt, iet, LIO] at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 35.
```

I looked in the file in question and `freeenas` was there
```
my $zfs_unknown_scsi_provider = sub {
    my ($provider) = @_;

    die "$provider: unknown iscsi provider. Available [comstar, freenas, istgt, iet, LIO]";
};
```

I restarted the PVE Host in question then tried to start the VM again, and it started successfully.

So I ran a test on another node, and got the same result. But instead of restarting the host, I restarted the `pve-ha-lrm` service.

I noticed that I had not restarted the host since installing this package. Have you restarted the HA service or Host itself since installing this package?

**Comment by TheGrandWazoo** [comment]
Usually I do a 'pvedaemon restart', 'pveproxy restart', and 'pvestat restart' on each node after the initial install. pve-ha-lrm might be doing the same thing.

**Comment by chanster** [comment]
It does seem `pve-ha-lrm` is dependent on those other services. Tested restarting `pve-ha-lrm`, the other services stayed running and vice versa.

https://pve.proxmox.com/wiki/Service_daemons

I'm not confident, but maybe also restart `pve-ha-lrm` install/upgrade would resolve this issue as it seems this service doesn’t see the change in `ZFSPlugin.pm` until its restarted.

**Comment by TheGrandWazoo** [comment]
Will be closing due to possible fix from other issues submitted.
If you are still having  the issue, please reopen.
