### ISSUE TITLE
Unable to delete disks on iscsi storage or move from local to iSCSI

### ISSUE THREAD

**Issue by mkomarinski** [TheGrandWazoo/freenas-proxmox#91]
I've been playing around with this on the latest of everything:

TrueNAS 12.0-U1
Proxmox 6.3-3

I was able to create a new VM and create a disk using the iSCSI storage.  I can also move a disk from iSCSI to local.

Trying to delete a disk no longer in use gives me:

Cannot remove image, a guest with VMID '104' exists!
You can delete the image from the guest's hardware pane

Trying to move a disk from local to iSCSI gives a similar issue. I can delete the disk from the TrueNAS side by removing the zvol but it would be nice to manage all that from Proxmox.

**Comment by TheGrandWazoo** [comment]
I just created a new VM with an EFI and two Virtio disks attached to TrueNAS 12.0-U1 using Proxmox 6.3-3. I did not encounter any issues with deleting the second disk by itself. I then performed a 'remove' of the VM with the EFI and primary disk without issues. All disk were attached to the TrueNAS 12.0-U1 NAS.

Not sure is you have a snapshot of the 'syslog' output at the time but that could help. Also I believe the "Cannot remove image< a guest with VMID '104' exists" comes from an upper Proxmox module so not sure what is happening there.

**Comment by mkomarinski** [comment]
Here's what I have when i try to move a disk from local to iSCSI.  I'm able to create drives and attach to a VM

Jan 12 13:12:45 virtual pvedaemon[1127]: <root@pam> move disk VM 104: move --disk scsi0 --storage freenas-iscsi
Jan 12 13:12:46 virtual pvedaemon[1127]: <root@pam> starting task UPID:virtual:000052D7:000C3625:5FFDE69E:qmmove:104:root@pam:
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : create_lu(/dev/zvol/Pool2/vm-104-disk-0)
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Changing to v2.0 API's
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection successful to '192.168.100.18' using the 'http' protocol
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : successful : Server version: TrueNAS-12.0-U1"
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : TrueNAS Unformatted Version: 12000100
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : Using TrueNAS API version v2.0
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_globalconfiguration : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.100.18'
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_globalconfiguration : target_basename=iqn.2005-10.org.freenas.ctl
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::run_create_lu : called with (method=create_lu; param[0]=/dev/zvol/Pool2/vm-104-disk-0)
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_first_available_lunid : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.100.18'
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 756.
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : successful : 
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target_to_extent : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.100.18'
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target_to_extent : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_first_available_lunid : 0
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : called with (method=create_lu; result_value_type=name; object=/dev/zvol/Pool2/vm-104-disk-0)
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_list_lu : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.100.18'
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.100.18'
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 756.
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : successful : 
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_list_lu : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::run_list_lu(/dev/zvol/Pool2/vm-104-disk-0) : name : lun not found
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.100.18'
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : successful
Jan 12 13:12:46 virtual pvedaemon[21207]: Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 756.
Jan 12 13:12:46 virtual pvedaemon[21207]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : successful : 
Jan 12 13:12:46 virtual pvedaemon[21207]: storage migration failed: error during cfs-locked 'storage-freenas-iscsi' operation: Unable to find the target id for iqn.2005-10.org.freenas.ctl:vm-0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 264.
Jan 12 13:12:47 virtual pvedaemon[1127]: <root@pam> end task UPID:virtual:000052D7:000C3625:5FFDE69E:qmmove:104:root@pam: storage migration failed: error during cfs-locked 'storage-freenas-iscsi' operation: Unable to find the target id for iqn.2005-10.org.freenas.ctl:vm-0 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 264.

**Comment by mkomarinski** [comment]
Welp that was dumb.  I have migrations working (somewhere along the way I deleted the target) and I forgot to remove the unused disk from the host configuration as detaching it doesn't remove it from the host.  Once I realized my error I'm able to remove the disks.
