### ISSUE TITLE
Unable to connect to the FreeNAS API service using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375.

### ISSUE THREAD

**Issue by scottthepotter** [TheGrandWazoo/freenas-proxmox#92]
I just went through and updated this to utilize the new repo. It was working before. After not being able to start the VM I went back and recreated the SSH keys and copied them to the FreeNAS server, went back through the install instructions and then restarted the ProxMox host. Upon restarting I still get the above error message.

Here is a tail from the syslog when attempting to start the VM:
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: start VM 109: UPID:proxmoxpoc:00000CA7:0000EC79:60280958:qmstart:109:root@pam:
Feb 13 10:16:08 proxmoxpoc pvedaemon[1064]: <root@pam> starting task UPID:proxmoxpoc:00000CA7:0000EC79:60280958:qmstart:109:root@pam:
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : list_lu(/dev/zvol/tank/iscsi-zfs/vm-109-disk-0)
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response code: 401
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: [ERROR]FreeNAS::API::PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Response content:
Feb 13 10:16:08 proxmoxpoc pvedaemon[3239]: Unable to connect to the FreeNAS API service at '10.1.1.17' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375.
Feb 13 10:16:08 proxmoxpoc pvedaemon[1064]: <root@pam> end task UPID:proxmoxpoc:00000CA7:0000EC79:60280958:qmstart:109:root@pam: Unable to connect to the FreeNAS API service at '10.1.1.17' using the 'http' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375.

**Comment by scottthepotter** [comment]
Nevermind, solved the problem.

**Comment by TheGrandWazoo** [comment]
Closing issue due to user resolved.

**Comment by spynick** [comment]
Ok, and what was the solution as I do have the same issue

**Comment by scottthepotter** [comment]
In my case it was PIBCAM (problem in between chair and monitor ;-). We had a sysadmin leave and we changed passwords and it didn't occur to me that changing the root password broke the handshake. Until later.

**Comment by TheGrandWazoo** [comment]
Thank you for posting your resolution.
I am currently trying to do "Tokens" so it might be a better choice for many.

**Comment by spynick** [comment]
Well, thanks for that hint. Did change the password back to it's original - changed it as well. But still the same error. Rebooted, recreated the SSH Certs and so on. Still the same issue.

Do I need to delete/recreate something else for handling the handshake?

Thanks

**Comment by scottthepotter** [comment]
After I realized I had changed the password I just made sure I updated the same password that I had changed on the FreeNAS/TrueNAS side on the ProxMox side
