### ISSUE TITLE
Migrations fails with could not find lu_name for zvol

### ISSUE THREAD

**Issue by townlema** [TheGrandWazoo/freenas-proxmox#96]
Running the following on a proxmox 636 server I get.  Its intermittent, sometimes it works the first time other times it takes 10 attempts.  Anyone else experienced this?  I'm not sure its related to the freenas-proxmox support or not but thought I would start here.

> qm migrate 103  pve2 --online
2021-04-09 17:28:32 starting migration of VM 103 to node 'pve2' (192.168.1.181)
2021-04-09 17:28:32 ERROR: Failed to sync data - Could not find lu_name for zvol vm-103-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 118.
2021-04-09 17:28:32 aborting phase 1 - cleanup resources
2021-04-09 17:28:32 ERROR: migration aborted (duration 00:00:00): Failed to sync data - Could not find lu_name for zvol vm-103-disk-0 at /usr/share/perl5/PVE/Storage/ZFSPlugin.pm line 118.
migration aborted

**Comment by TheGrandWazoo** [comment]
There should be more output from the syslog from the FreeNAS plugin. That could help me figure out the issue.

**Comment by townlema** [comment]
yep, sorry - see below:

Apr 14 23:57:16 pve3 pvedaemon[13361]: <root@pam> starting task UPID:pve3:000068A6:00BCB23E:6077653C:qmigrate:104:root@pam:
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::run_lun_command : list_lu(/dev/zvol/pool1/vms/vm-104-disk-0)
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : Changing to v2.0 API's
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_connect : REST connection successful to '192.168.1.171' using the 'http' protocol
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : successful : Server version: TrueNAS-12.0-U2.1"
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : TrueNAS Unformatted Version: 12000201
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_check : Using TrueNAS API version v2.0
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_globalconfiguration : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.1.171'
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_globalconfiguration : target_basename=iqn.2005-10.org.freenas.ctl
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : called with (method=list_lu; result_value_type=name; object=/dev/zvol/pool1/vms/vm-104-disk-0)
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_list_lu : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.1.171'
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.1.171'
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_get_targetid : successful : 3
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target_to_extent : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.1.171'
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_target_to_extent : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_extent : called
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : called for host '192.168.1.171'
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_api_call : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_iscsi_get_extent : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::freenas_list_lu : successful
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-102-disk-0' and '/dev/zvol/pool1/vms/vm-104-disk-0'
Apr 14 23:57:16 pve3 pvedaemon[26790]: PVE::Storage::LunCmd::FreeNAS::run_list_lu(/dev/zvol/pool1/vms/vm-104-disk-0) : name : lun not found
Apr 14 23:57:16 pve3 pvedaemon[26790]: migration aborted
Apr 14 23:57:16 pve3 pvedaemon[13361]: <root@pam> end task UPID:pve3:000068A6:00BCB23E:6077653C:qmigrate:104:root@pam: migration aborted

**Comment by TheGrandWazoo** [comment]
So it is looking for '/dev/zvol/pool1/vms/vm-104-disk-0' but only has 'zvol/pool1/vms/vm-102-disk-0' in its list.
FreeNAS only returned the 'zvol/pool1/vms/vm-102-disk-0'

Don't worry about the '/dev/' because that is added on the compare line of the code. Line #210 in FreeNAS.pm.

Look at your TrueNAS and see what it has in the Pool.

**Comment by townlema** [comment]
all my vm disks are there but as mentioned if I try the migration a number of times it eventually works:

root@truenas[/dev/zvol/pool1/vms]# ls -l
total 0
crw-r-----  1 root  operator  0x72 Apr  7 09:04 vm-100-disk-0
crw-r-----  1 root  operator  0x9f Apr  7 10:54 vm-100-state-ss1
crw-r-----  1 root  operator  0xa1 Apr  8 11:25 vm-101-disk-0
crw-r-----  1 root  operator  0xa2 Apr  9 12:26 vm-102-disk-0
crw-r-----  1 root  operator  0xa3 Apr  9 14:13 vm-103-disk-0
crw-r-----  1 root  operator  0xa8 Apr 13 18:16 vm-104-disk-0
crw-r-----  1 root  operator  0xab Apr 15 10:17 vm-105-disk-0
crw-r-----  1 root  operator  0xac Apr 15 10:36 vm-105-disk-1
crw-r-----  1 root  operator  0xad Apr 15 14:35 vm-105-disk-2
root@truenas[/dev/zvol/pool1/vms]#

**Comment by townlema** [comment]
strange, as it only seems to get 1 disk back when it queries truenas and it seems random what disk it gets back and then "eventually" it gets the right disk.  See below on the verifies it does for each migration I try until it gets a hit on the correct single disk/lun it gets back from truenas.  It took 20 attempts to migrate until it got the disk/lun match.  Each line below is a migration attempt in the web gui:

root@pve:~# grep -i verifing /var/log/syslog
Apr 17 18:34:00 pve pvedaemon[32153]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:39:09 pve pvedaemon[710]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-105-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:39:09 pve pvedaemon[710]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-105-disk-1' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:39:09 pve pvedaemon[710]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-105-disk-2' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:40:24 pve pvedaemon[958]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:41:13 pve pvedaemon[1123]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-103-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:41:33 pve pvedaemon[1183]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-104-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:41:50 pve pvedaemon[1242]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:42:07 pve pvedaemon[1319]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-105-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:42:07 pve pvedaemon[1319]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-105-disk-1' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:42:07 pve pvedaemon[1319]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-105-disk-2' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:42:21 pve pvedaemon[1350]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:42:37 pve pvedaemon[1409]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:42:54 pve pvedaemon[1474]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-104-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:43:06 pve pvedaemon[1515]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:45:59 pve pvedaemon[2047]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:46:21 pve pvedaemon[2112]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:46:37 pve pvedaemon[2172]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-103-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:46:53 pve pvedaemon[2213]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-101-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:47:12 pve pvedaemon[2276]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-100-state-ss1' and '/dev/zvol/pool1/vms/vm-100-disk-0'
Apr 17 18:47:12 pve pvedaemon[2276]: PVE::Storage::LunCmd::FreeNAS::run_list_lu : Verifing 'zvol/pool1/vms/vm-100-disk-0' and '/dev/zvol/pool1/vms/vm-100-disk-0'

**Comment by townlema** [comment]
apologies, lack of knowledge on my side.  Now I understand and things work fine - thanks

**Comment by miguelangel-nubla** [comment]
@townlema could you elaborate? I am hitting similar errors and I have no experience with iSCSI
