### ISSUE TITLE
Unable to connect to the FreeNAS API service at 'hostname' using the 'https' protocol

### ISSUE THREAD

**Issue by damjankumin** [TheGrandWazoo/freenas-proxmox#99]
Hello,

I successfully installed plugin, which may be the best thing that happened to Proxmox. Now I followed guide, connected successfully to the ZFS, I can see size and stuff but as soon as I want to do anything with VM, namely create or start, i get:

Unable to connect to the FreeNAS API service at 'hostname' using the 'https' protocol at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 375. (500)

I tried to change this with tick in setting for this storage, to use https and the result is same. Can anyone help? I am at the verge to have the perfect setup :) Thank you for any assistance!

rgD

**Comment by damjankumin** [comment]
OK resolved issue - I actually have to leave in TrueNAS tick "enable root password login" enable. Strange. Now I am faced with completely different issue:

```
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 566.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 756.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 587.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 566.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 566.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 756.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 566.
Use of uninitialized value $target_id in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 756.
TASK ERROR: unable to create VM 104 - Unable to find the target id for iqn.2005-10.org.freenas.ctl at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 264.
```

Any info about this? I should probably open new issue for it, right? :)

**Comment by TheGrandWazoo** [comment]
Seems like it can't find 'zfsoveriscsi' on the TrueNAS server.

"Base Name" under "Target Global Config" Tab should be "iqn.2005-10.org.freenas.ctl"
Then a "Target Name" under the Targets tab should be "zfsoveriscsi"

**Comment by TheGrandWazoo** [comment]
And yes the Root needs to be enabled for the API's, for now. I am trying to figure out a dynamic way to select a Username/Password or a Token in Proxmox so it removed the Username/Password requirement but still need it for legacy FreeNAS/TrueNAS configurations.

**Comment by damjankumin** [comment]
OK so I have done a correct job in configuring. I have:
Target in global config: iqn.2005-10.org.freenas.ctl
Target name in basic info under targets tab: zfsoveriscsi

in Proxmox I have: target name under general tab in ZFS over iSCSI: iqn.2005-10.org.freenas.ctl:zfsoveriscsi

I do have connection towards it, I can see size and everytging but no operation is possible. I have TrueNAS 12 U3.1 and Proxmox version 6.4-4. Anything else can check? Some logs for you? SC?
